//! Cryptographic primitives for Gyza.
//!
//! Three functions matter:
//!
//!   - [`hash`] — BLAKE3 (32-byte output) over a byte slice.
//!   - [`derive_seed`] — BLAKE3 keyed-mode "HKDF-equivalent" used to
//!     derive subkeys from a master seed. Matches the Python
//!     `_derive_seed(master, context, info)` exactly.
//!   - [`Signer`] — Ed25519 signing/verifying around a 32-byte seed.
//!
//! Cross-language parity is mechanically checked: the test module at
//! the bottom of this file fixes a master seed and verifies the
//! derived bytes match values generated by the Python reference.
//! When you change anything in this module, regenerate the fixtures
//! with `gyza-rs/scripts/regenerate_crypto_fixtures.py` (TODO).

use blake3::Hasher;
use ed25519_dalek::{Signature, SigningKey, Verifier, VerifyingKey};

/// Length of an Ed25519 public key in bytes (32).
pub const ED25519_PUBKEY_LEN: usize = 32;
/// Length of an Ed25519 signing seed in bytes (32).
pub const ED25519_SEED_LEN: usize = 32;
/// Length of an Ed25519 signature in bytes (64).
pub const ED25519_SIG_LEN: usize = 64;
/// Length of a BLAKE3 hash in bytes (32).
pub const BLAKE3_HASH_LEN: usize = 32;

/// Errors that can arise from this crate's operations.
#[derive(Debug, thiserror::Error)]
pub enum CryptoError {
    #[error("invalid seed length: expected {expected}, got {got}")]
    InvalidSeedLength { expected: usize, got: usize },
    #[error("invalid signature length: expected {expected}, got {got}")]
    InvalidSignatureLength { expected: usize, got: usize },
    #[error("invalid public key length: expected {expected}, got {got}")]
    InvalidPubkeyLength { expected: usize, got: usize },
    #[error("signature verification failed")]
    VerificationFailed,
    #[error("hex decoding failed: {0}")]
    HexDecode(#[from] hex::FromHexError),
}

/// BLAKE3 hash of `data`. Returns 32 bytes.
///
/// Equivalent to Python `blake3.blake3(data).digest()`.
#[inline]
pub fn hash(data: &[u8]) -> [u8; BLAKE3_HASH_LEN] {
    *blake3::hash(data).as_bytes()
}

/// Hex-encoded BLAKE3 hash. Convenience wrapper around [`hash`].
///
/// Equivalent to Python `blake3.blake3(data).hexdigest()`.
#[inline]
pub fn hash_hex(data: &[u8]) -> String {
    hex::encode(hash(data))
}

/// Derive a 32-byte subseed from a 32-byte master seed plus a context
/// string and an info string.
///
/// Algorithm matches Python `gyza.identity._derive_seed` exactly:
///
/// ```text
/// _derive_seed(master, context, info)
///     = blake3(context || b"|" || info, key=master).digest()
/// ```
///
/// BLAKE3 keyed mode is the cross-language equivalent. Both Python's
/// `blake3.blake3(data, key=master)` and Rust's
/// `blake3::Hasher::new_keyed(&master).update(data).finalize()`
/// produce byte-identical output.
pub fn derive_seed(master: &[u8; 32], context: &[u8], info: &[u8]) -> [u8; 32] {
    let mut hasher = Hasher::new_keyed(master);
    hasher.update(context);
    hasher.update(b"|");
    hasher.update(info);
    *hasher.finalize().as_bytes()
}

/// Wrapper around an Ed25519 signing key derived from a 32-byte seed.
///
/// Constructed via [`Signer::from_seed`]. The `seed` is what's stored
/// on disk (e.g., `~/.gyza/compositor.key`) and HKDF-derived from a
/// master seed. The actual signing key (`SigningKey`) is materialized
/// internally.
pub struct Signer {
    signing_key: SigningKey,
}

impl Signer {
    /// Construct a signer from a 32-byte seed.
    pub fn from_seed(seed: &[u8; ED25519_SEED_LEN]) -> Self {
        let signing_key = SigningKey::from_bytes(seed);
        Self { signing_key }
    }

    /// Return the public key as 32 bytes.
    pub fn pubkey_bytes(&self) -> [u8; ED25519_PUBKEY_LEN] {
        self.signing_key.verifying_key().to_bytes()
    }

    /// Hex-encoded lowercase public key (64 chars).
    ///
    /// Equivalent to Python's hex serialization of the Ed25519
    /// public key bytes.
    pub fn pubkey_hex(&self) -> String {
        hex::encode(self.pubkey_bytes())
    }

    /// Produce an Ed25519 signature over `data`. 64-byte output.
    ///
    /// Ed25519 is deterministic per (key, message), so two signers
    /// with the same seed produce the same signature for the same
    /// data. This is what makes cross-language parity testing
    /// possible.
    pub fn sign(&self, data: &[u8]) -> [u8; ED25519_SIG_LEN] {
        // Sign trait is in scope via the prelude when needed.
        use ed25519_dalek::Signer as _;
        self.signing_key.sign(data).to_bytes()
    }

    /// Hex-encoded lowercase signature (128 chars).
    pub fn sign_hex(&self, data: &[u8]) -> String {
        hex::encode(self.sign(data))
    }
}

/// Verify an Ed25519 signature against a public key.
///
/// Returns `Ok(())` on valid signature, `Err(CryptoError::VerificationFailed)`
/// on mismatch. Other errors signal malformed inputs.
pub fn verify(pubkey: &[u8], data: &[u8], signature: &[u8]) -> Result<(), CryptoError> {
    if pubkey.len() != ED25519_PUBKEY_LEN {
        return Err(CryptoError::InvalidPubkeyLength {
            expected: ED25519_PUBKEY_LEN,
            got: pubkey.len(),
        });
    }
    if signature.len() != ED25519_SIG_LEN {
        return Err(CryptoError::InvalidSignatureLength {
            expected: ED25519_SIG_LEN,
            got: signature.len(),
        });
    }
    let pk_array: [u8; ED25519_PUBKEY_LEN] = pubkey.try_into().expect("length checked above");
    let verifying =
        VerifyingKey::from_bytes(&pk_array).map_err(|_| CryptoError::VerificationFailed)?;
    let sig_array: [u8; ED25519_SIG_LEN] = signature.try_into().expect("length checked above");
    let sig = Signature::from_bytes(&sig_array);
    verifying
        .verify(data, &sig)
        .map_err(|_| CryptoError::VerificationFailed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use hex_literal::hex;

    /// Master seed used as a fixed test vector. The corresponding
    /// fixtures in this module were generated by feeding this seed
    /// to Python's `gyza.identity._derive_seed`.
    const TEST_MASTER: [u8; 32] = hex!(
        "0102030405060708090a0b0c0d0e0f10"
        "1112131415161718191a1b1c1d1e1f20"
    );

    #[test]
    fn blake3_hash_known_vectors() {
        // BLAKE3 of empty input. From the BLAKE3 spec's official
        // test vectors (https://github.com/BLAKE3-team/BLAKE3/blob/master/test_vectors/test_vectors.json).
        let h = hash(b"");
        assert_eq!(
            hex::encode(h),
            "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262",
        );

        // BLAKE3 of the byte sequence 0..1 (one byte: 0x00). Per
        // the official test vectors.
        let h2 = hash(&[0u8]);
        assert_eq!(
            hex::encode(h2),
            "2d3adedff11b61f14c886e35afa036736dcd87a74d27b5c1510225d0f592e213",
        );
    }

    #[test]
    fn derive_seed_parity_with_python() {
        // Python reference:
        //   master = bytes.fromhex("0102...20")
        //   blake3.blake3(b"gyza.compositor.ed25519.v1|", key=master).digest()
        let compositor_seed = derive_seed(&TEST_MASTER, b"gyza.compositor.ed25519.v1", b"");
        // Expected = blake3 keyed(master) over "gyza.compositor.ed25519.v1|"
        // (the trailing pipe; info=b"" is appended after the pipe).
        // Fixture generated by gyza-rs/scripts/regenerate_crypto_fixtures.py
        // at Session 21 (commit forthcoming).
        assert_eq!(
            hex::encode(compositor_seed),
            "774e35bfe14c538dab4efacfeb02b0d9ec598a9023e3c98d4ddf3c3899ed0182",
        );

        // Same derivation with non-empty info — agent issuance path.
        let agent_seed = derive_seed(&TEST_MASTER, b"gyza.agent.ed25519.v1", b"agent-0001");
        assert_eq!(
            hex::encode(agent_seed),
            "382c116f42ea4526dab2f5dc60dcda12a3bf44da7715c1c45296a630d393e2f3",
        );
    }

    #[test]
    fn ed25519_sign_verify_roundtrip() {
        let seed = derive_seed(&TEST_MASTER, b"gyza.compositor.ed25519.v1", b"");
        let signer = Signer::from_seed(&seed);

        let msg = b"hello gyza";
        let sig = signer.sign(msg);

        // Roundtrip should succeed.
        verify(&signer.pubkey_bytes(), msg, &sig).expect("verify must succeed");

        // Tampering breaks verification.
        let mut tampered_sig = sig;
        tampered_sig[0] ^= 0x01;
        let err = verify(&signer.pubkey_bytes(), msg, &tampered_sig);
        assert!(matches!(err, Err(CryptoError::VerificationFailed)));

        // Tampered message also breaks verification.
        let err = verify(&signer.pubkey_bytes(), b"hello gyzb", &sig);
        assert!(matches!(err, Err(CryptoError::VerificationFailed)));
    }

    #[test]
    fn ed25519_pubkey_parity_with_python() {
        // Given the same compositor seed, the Ed25519 pubkey must
        // match Python's `Ed25519PrivateKey.from_private_bytes(seed)
        // .public_key().public_bytes_raw()` exactly.
        let seed = derive_seed(&TEST_MASTER, b"gyza.compositor.ed25519.v1", b"");
        let signer = Signer::from_seed(&seed);
        // Fixture generated by gyza-rs/scripts/regenerate_crypto_fixtures.py.
        assert_eq!(
            signer.pubkey_hex(),
            "08ed03d0cb5efe9152a79430ddd86a97286d760bdb5955fea3688e8bb9a13ab9",
        );
    }

    #[test]
    fn ed25519_signature_parity_with_python() {
        // Ed25519 is deterministic. Given the same seed and message,
        // Rust's ed25519-dalek and Python's cryptography Ed25519
        // produce byte-identical signatures.
        let seed = derive_seed(&TEST_MASTER, b"gyza.compositor.ed25519.v1", b"");
        let signer = Signer::from_seed(&seed);
        let msg = b"hello gyza";
        // Fixture generated by gyza-rs/scripts/regenerate_crypto_fixtures.py.
        assert_eq!(
            signer.sign_hex(msg),
            "cee3aece6183b50b280bc41ad879abc95e9bafa5039a2d3bccb6e4598e3765ac\
             38c61d99cc4584f491b33436fd2592ba5cc921fa9baab6e19e4326582a91f507",
        );
    }

    #[test]
    fn invalid_input_lengths_rejected() {
        let bad_short = [0u8; 16];
        let bad_long = [0u8; 100];
        assert!(matches!(
            verify(&bad_short, b"x", &[0u8; ED25519_SIG_LEN]),
            Err(CryptoError::InvalidPubkeyLength { .. })
        ));
        assert!(matches!(
            verify(&[0u8; ED25519_PUBKEY_LEN], b"x", &bad_long),
            Err(CryptoError::InvalidSignatureLength { .. })
        ));
    }
}
