// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: netd.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_GetNodeInfo_FullMethodName = "/netd.NodeService/GetNodeInfo"
	NodeService_GetStatus_FullMethodName   = "/netd.NodeService/GetStatus"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// NodeService — local node identity & status
// =============================================================================
type NodeServiceClient interface {
	GetNodeInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeInfo, error)
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetNodeInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, NodeService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// =============================================================================
// NodeService — local node identity & status
// =============================================================================
type NodeServiceServer interface {
	GetNodeInfo(context.Context, *Empty) (*NodeInfo, error)
	GetStatus(context.Context, *Empty) (*NodeStatus, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) GetNodeInfo(context.Context, *Empty) (*NodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNodeServiceServer) GetStatus(context.Context, *Empty) (*NodeStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetNodeInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _NodeService_GetNodeInfo_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NodeService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netd.proto",
}

const (
	DiscoveryService_PublishAgent_FullMethodName   = "/netd.DiscoveryService/PublishAgent"
	DiscoveryService_FindAgents_FullMethodName     = "/netd.DiscoveryService/FindAgents"
	DiscoveryService_UnpublishAgent_FullMethodName = "/netd.DiscoveryService/UnpublishAgent"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// DiscoveryService — find agents by capability
// =============================================================================
type DiscoveryServiceClient interface {
	PublishAgent(ctx context.Context, in *AgentAdvertisement, opts ...grpc.CallOption) (*PublishResult, error)
	FindAgents(ctx context.Context, in *AgentQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentAdvertisement], error)
	UnpublishAgent(ctx context.Context, in *UnpublishRequest, opts ...grpc.CallOption) (*Empty, error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) PublishAgent(ctx context.Context, in *AgentAdvertisement, opts ...grpc.CallOption) (*PublishResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResult)
	err := c.cc.Invoke(ctx, DiscoveryService_PublishAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) FindAgents(ctx context.Context, in *AgentQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentAdvertisement], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DiscoveryService_ServiceDesc.Streams[0], DiscoveryService_FindAgents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentQuery, AgentAdvertisement]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiscoveryService_FindAgentsClient = grpc.ServerStreamingClient[AgentAdvertisement]

func (c *discoveryServiceClient) UnpublishAgent(ctx context.Context, in *UnpublishRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DiscoveryService_UnpublishAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations must embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
//
// =============================================================================
// DiscoveryService — find agents by capability
// =============================================================================
type DiscoveryServiceServer interface {
	PublishAgent(context.Context, *AgentAdvertisement) (*PublishResult, error)
	FindAgents(*AgentQuery, grpc.ServerStreamingServer[AgentAdvertisement]) error
	UnpublishAgent(context.Context, *UnpublishRequest) (*Empty, error)
	mustEmbedUnimplementedDiscoveryServiceServer()
}

// UnimplementedDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) PublishAgent(context.Context, *AgentAdvertisement) (*PublishResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishAgent not implemented")
}
func (UnimplementedDiscoveryServiceServer) FindAgents(*AgentQuery, grpc.ServerStreamingServer[AgentAdvertisement]) error {
	return status.Errorf(codes.Unimplemented, "method FindAgents not implemented")
}
func (UnimplementedDiscoveryServiceServer) UnpublishAgent(context.Context, *UnpublishRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnpublishAgent not implemented")
}
func (UnimplementedDiscoveryServiceServer) mustEmbedUnimplementedDiscoveryServiceServer() {}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue()                          {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_PublishAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentAdvertisement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).PublishAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_PublishAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).PublishAgent(ctx, req.(*AgentAdvertisement))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_FindAgents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServiceServer).FindAgents(m, &grpc.GenericServerStream[AgentQuery, AgentAdvertisement]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiscoveryService_FindAgentsServer = grpc.ServerStreamingServer[AgentAdvertisement]

func _DiscoveryService_UnpublishAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).UnpublishAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_UnpublishAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).UnpublishAgent(ctx, req.(*UnpublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishAgent",
			Handler:    _DiscoveryService_PublishAgent_Handler,
		},
		{
			MethodName: "UnpublishAgent",
			Handler:    _DiscoveryService_UnpublishAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FindAgents",
			Handler:       _DiscoveryService_FindAgents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "netd.proto",
}

const (
	PeerService_Connect_FullMethodName     = "/netd.PeerService/Connect"
	PeerService_Disconnect_FullMethodName  = "/netd.PeerService/Disconnect"
	PeerService_ListPeers_FullMethodName   = "/netd.PeerService/ListPeers"
	PeerService_GetPeerInfo_FullMethodName = "/netd.PeerService/GetPeerInfo"
)

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// PeerService — direct peer connections
// =============================================================================
type PeerServiceClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResult, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Empty, error)
	ListPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerList, error)
	GetPeerInfo(ctx context.Context, in *PeerInfoRequest, opts ...grpc.CallOption) (*PeerInfo, error)
}

type peerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerServiceClient(cc grpc.ClientConnInterface) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResult)
	err := c.cc.Invoke(ctx, PeerService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PeerService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ListPeers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PeerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerList)
	err := c.cc.Invoke(ctx, PeerService_ListPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) GetPeerInfo(ctx context.Context, in *PeerInfoRequest, opts ...grpc.CallOption) (*PeerInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerInfo)
	err := c.cc.Invoke(ctx, PeerService_GetPeerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
// All implementations must embed UnimplementedPeerServiceServer
// for forward compatibility.
//
// =============================================================================
// PeerService — direct peer connections
// =============================================================================
type PeerServiceServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectResult, error)
	Disconnect(context.Context, *DisconnectRequest) (*Empty, error)
	ListPeers(context.Context, *Empty) (*PeerList, error)
	GetPeerInfo(context.Context, *PeerInfoRequest) (*PeerInfo, error)
	mustEmbedUnimplementedPeerServiceServer()
}

// UnimplementedPeerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerServiceServer struct{}

func (UnimplementedPeerServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPeerServiceServer) Disconnect(context.Context, *DisconnectRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedPeerServiceServer) ListPeers(context.Context, *Empty) (*PeerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeers not implemented")
}
func (UnimplementedPeerServiceServer) GetPeerInfo(context.Context, *PeerInfoRequest) (*PeerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerInfo not implemented")
}
func (UnimplementedPeerServiceServer) mustEmbedUnimplementedPeerServiceServer() {}
func (UnimplementedPeerServiceServer) testEmbeddedByValue()                     {}

// UnsafePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServiceServer will
// result in compilation errors.
type UnsafePeerServiceServer interface {
	mustEmbedUnimplementedPeerServiceServer()
}

func RegisterPeerServiceServer(s grpc.ServiceRegistrar, srv PeerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPeerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerService_ServiceDesc, srv)
}

func _PeerService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_ListPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ListPeers(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_GetPeerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).GetPeerInfo(ctx, req.(*PeerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerService_ServiceDesc is the grpc.ServiceDesc for PeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _PeerService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _PeerService_Disconnect_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _PeerService_ListPeers_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _PeerService_GetPeerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netd.proto",
}

const (
	MessageService_Send_FullMethodName      = "/netd.MessageService/Send"
	MessageService_Broadcast_FullMethodName = "/netd.MessageService/Broadcast"
	MessageService_Subscribe_FullMethodName = "/netd.MessageService/Subscribe"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// MessageService — send arbitrary messages to peers
// =============================================================================
type MessageServiceClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResult, error)
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResult, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingMessage], error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResult)
	err := c.cc.Invoke(ctx, MessageService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResult)
	err := c.cc.Invoke(ctx, MessageService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IncomingMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MessageService_ServiceDesc.Streams[0], MessageService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, IncomingMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageService_SubscribeClient = grpc.ServerStreamingClient[IncomingMessage]

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
//
// =============================================================================
// MessageService — send arbitrary messages to peers
// =============================================================================
type MessageServiceServer interface {
	Send(context.Context, *SendRequest) (*SendResult, error)
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResult, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[IncomingMessage]) error
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) Send(context.Context, *SendRequest) (*SendResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMessageServiceServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedMessageServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[IncomingMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, IncomingMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MessageService_SubscribeServer = grpc.ServerStreamingServer[IncomingMessage]

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MessageService_Send_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _MessageService_Broadcast_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _MessageService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "netd.proto",
}

const (
	DHTService_Put_FullMethodName    = "/netd.DHTService/Put"
	DHTService_Get_FullMethodName    = "/netd.DHTService/Get"
	DHTService_Delete_FullMethodName = "/netd.DHTService/Delete"
)

// DHTServiceClient is the client API for DHTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// DHTService — direct DHT operations
// =============================================================================
type DHTServiceClient interface {
	Put(ctx context.Context, in *DHTRecord, opts ...grpc.CallOption) (*DHTResult, error)
	Get(ctx context.Context, in *DHTKey, opts ...grpc.CallOption) (*DHTRecord, error)
	Delete(ctx context.Context, in *DHTKey, opts ...grpc.CallOption) (*DHTResult, error)
}

type dHTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDHTServiceClient(cc grpc.ClientConnInterface) DHTServiceClient {
	return &dHTServiceClient{cc}
}

func (c *dHTServiceClient) Put(ctx context.Context, in *DHTRecord, opts ...grpc.CallOption) (*DHTResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DHTResult)
	err := c.cc.Invoke(ctx, DHTService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHTServiceClient) Get(ctx context.Context, in *DHTKey, opts ...grpc.CallOption) (*DHTRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DHTRecord)
	err := c.cc.Invoke(ctx, DHTService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dHTServiceClient) Delete(ctx context.Context, in *DHTKey, opts ...grpc.CallOption) (*DHTResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DHTResult)
	err := c.cc.Invoke(ctx, DHTService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DHTServiceServer is the server API for DHTService service.
// All implementations must embed UnimplementedDHTServiceServer
// for forward compatibility.
//
// =============================================================================
// DHTService — direct DHT operations
// =============================================================================
type DHTServiceServer interface {
	Put(context.Context, *DHTRecord) (*DHTResult, error)
	Get(context.Context, *DHTKey) (*DHTRecord, error)
	Delete(context.Context, *DHTKey) (*DHTResult, error)
	mustEmbedUnimplementedDHTServiceServer()
}

// UnimplementedDHTServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDHTServiceServer struct{}

func (UnimplementedDHTServiceServer) Put(context.Context, *DHTRecord) (*DHTResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedDHTServiceServer) Get(context.Context, *DHTKey) (*DHTRecord, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDHTServiceServer) Delete(context.Context, *DHTKey) (*DHTResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDHTServiceServer) mustEmbedUnimplementedDHTServiceServer() {}
func (UnimplementedDHTServiceServer) testEmbeddedByValue()                    {}

// UnsafeDHTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DHTServiceServer will
// result in compilation errors.
type UnsafeDHTServiceServer interface {
	mustEmbedUnimplementedDHTServiceServer()
}

func RegisterDHTServiceServer(s grpc.ServiceRegistrar, srv DHTServiceServer) {
	// If the following call pancis, it indicates UnimplementedDHTServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DHTService_ServiceDesc, srv)
}

func _DHTService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHTRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHTServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHTService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHTServiceServer).Put(ctx, req.(*DHTRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHTService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHTKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHTServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHTService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHTServiceServer).Get(ctx, req.(*DHTKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _DHTService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DHTKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DHTServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DHTService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DHTServiceServer).Delete(ctx, req.(*DHTKey))
	}
	return interceptor(ctx, in, info, handler)
}

// DHTService_ServiceDesc is the grpc.ServiceDesc for DHTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DHTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.DHTService",
	HandlerType: (*DHTServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _DHTService_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DHTService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DHTService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netd.proto",
}

const (
	GossipService_JoinProject_FullMethodName     = "/netd.GossipService/JoinProject"
	GossipService_LeaveProject_FullMethodName    = "/netd.GossipService/LeaveProject"
	GossipService_PublishDelta_FullMethodName    = "/netd.GossipService/PublishDelta"
	GossipService_SubscribeDeltas_FullMethodName = "/netd.GossipService/SubscribeDeltas"
	GossipService_ListProjects_FullMethodName    = "/netd.GossipService/ListProjects"
)

// GossipServiceClient is the client API for GossipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// GossipService — cross-cluster blackboard delta sync via libp2p
// gossipsub. Each project has its own topic
// /gyza/project/{project_id}/blackboard. Deltas are signed at two
// layers: libp2p pubsub envelope (StrictSignatureVerification) and
// an app-layer Ed25519 signature over BLAKE3(delta_with_sig_zeroed).
//
// SubscribeDeltas is server-streaming; the daemon pushes deltas to
// every subscriber as they arrive on the project's topic. Multiple
// Python clients on one daemon can subscribe simultaneously without
// stepping on each other — the daemon fans out internally.
// =============================================================================
type GossipServiceClient interface {
	JoinProject(ctx context.Context, in *JoinProjectRequest, opts ...grpc.CallOption) (*JoinProjectResult, error)
	LeaveProject(ctx context.Context, in *LeaveProjectRequest, opts ...grpc.CallOption) (*Empty, error)
	PublishDelta(ctx context.Context, in *PublishDeltaRequest, opts ...grpc.CallOption) (*PublishDeltaResult, error)
	SubscribeDeltas(ctx context.Context, in *SubscribeDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlackboardDelta], error)
	ListProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectList, error)
}

type gossipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipServiceClient(cc grpc.ClientConnInterface) GossipServiceClient {
	return &gossipServiceClient{cc}
}

func (c *gossipServiceClient) JoinProject(ctx context.Context, in *JoinProjectRequest, opts ...grpc.CallOption) (*JoinProjectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinProjectResult)
	err := c.cc.Invoke(ctx, GossipService_JoinProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipServiceClient) LeaveProject(ctx context.Context, in *LeaveProjectRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GossipService_LeaveProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipServiceClient) PublishDelta(ctx context.Context, in *PublishDeltaRequest, opts ...grpc.CallOption) (*PublishDeltaResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishDeltaResult)
	err := c.cc.Invoke(ctx, GossipService_PublishDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipServiceClient) SubscribeDeltas(ctx context.Context, in *SubscribeDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlackboardDelta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GossipService_ServiceDesc.Streams[0], GossipService_SubscribeDeltas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeDeltasRequest, BlackboardDelta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GossipService_SubscribeDeltasClient = grpc.ServerStreamingClient[BlackboardDelta]

func (c *gossipServiceClient) ListProjects(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProjectList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectList)
	err := c.cc.Invoke(ctx, GossipService_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServiceServer is the server API for GossipService service.
// All implementations must embed UnimplementedGossipServiceServer
// for forward compatibility.
//
// =============================================================================
// GossipService — cross-cluster blackboard delta sync via libp2p
// gossipsub. Each project has its own topic
// /gyza/project/{project_id}/blackboard. Deltas are signed at two
// layers: libp2p pubsub envelope (StrictSignatureVerification) and
// an app-layer Ed25519 signature over BLAKE3(delta_with_sig_zeroed).
//
// SubscribeDeltas is server-streaming; the daemon pushes deltas to
// every subscriber as they arrive on the project's topic. Multiple
// Python clients on one daemon can subscribe simultaneously without
// stepping on each other — the daemon fans out internally.
// =============================================================================
type GossipServiceServer interface {
	JoinProject(context.Context, *JoinProjectRequest) (*JoinProjectResult, error)
	LeaveProject(context.Context, *LeaveProjectRequest) (*Empty, error)
	PublishDelta(context.Context, *PublishDeltaRequest) (*PublishDeltaResult, error)
	SubscribeDeltas(*SubscribeDeltasRequest, grpc.ServerStreamingServer[BlackboardDelta]) error
	ListProjects(context.Context, *Empty) (*ProjectList, error)
	mustEmbedUnimplementedGossipServiceServer()
}

// UnimplementedGossipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGossipServiceServer struct{}

func (UnimplementedGossipServiceServer) JoinProject(context.Context, *JoinProjectRequest) (*JoinProjectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinProject not implemented")
}
func (UnimplementedGossipServiceServer) LeaveProject(context.Context, *LeaveProjectRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveProject not implemented")
}
func (UnimplementedGossipServiceServer) PublishDelta(context.Context, *PublishDeltaRequest) (*PublishDeltaResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishDelta not implemented")
}
func (UnimplementedGossipServiceServer) SubscribeDeltas(*SubscribeDeltasRequest, grpc.ServerStreamingServer[BlackboardDelta]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeDeltas not implemented")
}
func (UnimplementedGossipServiceServer) ListProjects(context.Context, *Empty) (*ProjectList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedGossipServiceServer) mustEmbedUnimplementedGossipServiceServer() {}
func (UnimplementedGossipServiceServer) testEmbeddedByValue()                       {}

// UnsafeGossipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipServiceServer will
// result in compilation errors.
type UnsafeGossipServiceServer interface {
	mustEmbedUnimplementedGossipServiceServer()
}

func RegisterGossipServiceServer(s grpc.ServiceRegistrar, srv GossipServiceServer) {
	// If the following call pancis, it indicates UnimplementedGossipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GossipService_ServiceDesc, srv)
}

func _GossipService_JoinProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).JoinProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_JoinProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).JoinProject(ctx, req.(*JoinProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipService_LeaveProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).LeaveProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_LeaveProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).LeaveProject(ctx, req.(*LeaveProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipService_PublishDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishDeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).PublishDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_PublishDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).PublishDelta(ctx, req.(*PublishDeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipService_SubscribeDeltas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeDeltasRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GossipServiceServer).SubscribeDeltas(m, &grpc.GenericServerStream[SubscribeDeltasRequest, BlackboardDelta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GossipService_SubscribeDeltasServer = grpc.ServerStreamingServer[BlackboardDelta]

func _GossipService_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).ListProjects(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GossipService_ServiceDesc is the grpc.ServiceDesc for GossipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GossipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.GossipService",
	HandlerType: (*GossipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinProject",
			Handler:    _GossipService_JoinProject_Handler,
		},
		{
			MethodName: "LeaveProject",
			Handler:    _GossipService_LeaveProject_Handler,
		},
		{
			MethodName: "PublishDelta",
			Handler:    _GossipService_PublishDelta_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _GossipService_ListProjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDeltas",
			Handler:       _GossipService_SubscribeDeltas_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "netd.proto",
}

const (
	CapabilityService_IssueChallenge_FullMethodName     = "/netd.CapabilityService/IssueChallenge"
	CapabilityService_VerifyResponse_FullMethodName     = "/netd.CapabilityService/VerifyResponse"
	CapabilityService_PublishAttestation_FullMethodName = "/netd.CapabilityService/PublishAttestation"
	CapabilityService_FetchAttestation_FullMethodName   = "/netd.CapabilityService/FetchAttestation"
	CapabilityService_VerifyAttestation_FullMethodName  = "/netd.CapabilityService/VerifyAttestation"
)

// CapabilityServiceClient is the client API for CapabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// =============================================================================
// CapabilityService — proof-of-capability sybil resistance.
//
// A new node that wants Tier-3 DHT visibility must demonstrate it can
// actually execute agent tasks. It collects a signed AttestationCert
// from ≥2 of 3 existing Tier-3 validators by:
//
//  1. Each validator issues a Challenge (random task IDs from the
//     canonical eval suite, signed nonce, expiry).
//  2. The applicant executes the tasks locally and returns
//     ChallengeResponse with per-task ICP envelopes (proof of
//     execution by the claimed agent).
//  3. Each validator verifies the response and co-signs an
//     AttestationBody.
//  4. The applicant assembles AttestationCert from ≥2 cosignatures
//     and publishes it to the DHT at /gyza/attestations/{pubkey}.
//
// Other nodes that see Tier-3 advertisements check the cert via
// VerifyAttestation before trusting routing/work-claim signals from
// the advertiser.
//
// All sign/verify steps use proto.MarshalOptions{Deterministic: true}
// over the *Body message so cross-runtime reproduction is exact.
// =============================================================================
type CapabilityServiceClient interface {
	IssueChallenge(ctx context.Context, in *IssueChallengeRequest, opts ...grpc.CallOption) (*Challenge, error)
	VerifyResponse(ctx context.Context, in *VerifyResponseRequest, opts ...grpc.CallOption) (*VerifyResponseResult, error)
	PublishAttestation(ctx context.Context, in *AttestationCert, opts ...grpc.CallOption) (*PublishAttestationResult, error)
	FetchAttestation(ctx context.Context, in *FetchAttestationRequest, opts ...grpc.CallOption) (*AttestationCert, error)
	VerifyAttestation(ctx context.Context, in *AttestationCert, opts ...grpc.CallOption) (*VerifyAttestationResult, error)
}

type capabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityServiceClient(cc grpc.ClientConnInterface) CapabilityServiceClient {
	return &capabilityServiceClient{cc}
}

func (c *capabilityServiceClient) IssueChallenge(ctx context.Context, in *IssueChallengeRequest, opts ...grpc.CallOption) (*Challenge, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Challenge)
	err := c.cc.Invoke(ctx, CapabilityService_IssueChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) VerifyResponse(ctx context.Context, in *VerifyResponseRequest, opts ...grpc.CallOption) (*VerifyResponseResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponseResult)
	err := c.cc.Invoke(ctx, CapabilityService_VerifyResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) PublishAttestation(ctx context.Context, in *AttestationCert, opts ...grpc.CallOption) (*PublishAttestationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishAttestationResult)
	err := c.cc.Invoke(ctx, CapabilityService_PublishAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) FetchAttestation(ctx context.Context, in *FetchAttestationRequest, opts ...grpc.CallOption) (*AttestationCert, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttestationCert)
	err := c.cc.Invoke(ctx, CapabilityService_FetchAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) VerifyAttestation(ctx context.Context, in *AttestationCert, opts ...grpc.CallOption) (*VerifyAttestationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAttestationResult)
	err := c.cc.Invoke(ctx, CapabilityService_VerifyAttestation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityServiceServer is the server API for CapabilityService service.
// All implementations must embed UnimplementedCapabilityServiceServer
// for forward compatibility.
//
// =============================================================================
// CapabilityService — proof-of-capability sybil resistance.
//
// A new node that wants Tier-3 DHT visibility must demonstrate it can
// actually execute agent tasks. It collects a signed AttestationCert
// from ≥2 of 3 existing Tier-3 validators by:
//
//  1. Each validator issues a Challenge (random task IDs from the
//     canonical eval suite, signed nonce, expiry).
//  2. The applicant executes the tasks locally and returns
//     ChallengeResponse with per-task ICP envelopes (proof of
//     execution by the claimed agent).
//  3. Each validator verifies the response and co-signs an
//     AttestationBody.
//  4. The applicant assembles AttestationCert from ≥2 cosignatures
//     and publishes it to the DHT at /gyza/attestations/{pubkey}.
//
// Other nodes that see Tier-3 advertisements check the cert via
// VerifyAttestation before trusting routing/work-claim signals from
// the advertiser.
//
// All sign/verify steps use proto.MarshalOptions{Deterministic: true}
// over the *Body message so cross-runtime reproduction is exact.
// =============================================================================
type CapabilityServiceServer interface {
	IssueChallenge(context.Context, *IssueChallengeRequest) (*Challenge, error)
	VerifyResponse(context.Context, *VerifyResponseRequest) (*VerifyResponseResult, error)
	PublishAttestation(context.Context, *AttestationCert) (*PublishAttestationResult, error)
	FetchAttestation(context.Context, *FetchAttestationRequest) (*AttestationCert, error)
	VerifyAttestation(context.Context, *AttestationCert) (*VerifyAttestationResult, error)
	mustEmbedUnimplementedCapabilityServiceServer()
}

// UnimplementedCapabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityServiceServer struct{}

func (UnimplementedCapabilityServiceServer) IssueChallenge(context.Context, *IssueChallengeRequest) (*Challenge, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueChallenge not implemented")
}
func (UnimplementedCapabilityServiceServer) VerifyResponse(context.Context, *VerifyResponseRequest) (*VerifyResponseResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyResponse not implemented")
}
func (UnimplementedCapabilityServiceServer) PublishAttestation(context.Context, *AttestationCert) (*PublishAttestationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishAttestation not implemented")
}
func (UnimplementedCapabilityServiceServer) FetchAttestation(context.Context, *FetchAttestationRequest) (*AttestationCert, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchAttestation not implemented")
}
func (UnimplementedCapabilityServiceServer) VerifyAttestation(context.Context, *AttestationCert) (*VerifyAttestationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAttestation not implemented")
}
func (UnimplementedCapabilityServiceServer) mustEmbedUnimplementedCapabilityServiceServer() {}
func (UnimplementedCapabilityServiceServer) testEmbeddedByValue()                           {}

// UnsafeCapabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityServiceServer will
// result in compilation errors.
type UnsafeCapabilityServiceServer interface {
	mustEmbedUnimplementedCapabilityServiceServer()
}

func RegisterCapabilityServiceServer(s grpc.ServiceRegistrar, srv CapabilityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCapabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityService_ServiceDesc, srv)
}

func _CapabilityService_IssueChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).IssueChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_IssueChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).IssueChallenge(ctx, req.(*IssueChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_VerifyResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyResponseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).VerifyResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_VerifyResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).VerifyResponse(ctx, req.(*VerifyResponseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_PublishAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationCert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).PublishAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_PublishAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).PublishAttestation(ctx, req.(*AttestationCert))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_FetchAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).FetchAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_FetchAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).FetchAttestation(ctx, req.(*FetchAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_VerifyAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttestationCert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).VerifyAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_VerifyAttestation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).VerifyAttestation(ctx, req.(*AttestationCert))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityService_ServiceDesc is the grpc.ServiceDesc for CapabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "netd.CapabilityService",
	HandlerType: (*CapabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueChallenge",
			Handler:    _CapabilityService_IssueChallenge_Handler,
		},
		{
			MethodName: "VerifyResponse",
			Handler:    _CapabilityService_VerifyResponse_Handler,
		},
		{
			MethodName: "PublishAttestation",
			Handler:    _CapabilityService_PublishAttestation_Handler,
		},
		{
			MethodName: "FetchAttestation",
			Handler:    _CapabilityService_FetchAttestation_Handler,
		},
		{
			MethodName: "VerifyAttestation",
			Handler:    _CapabilityService_VerifyAttestation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "netd.proto",
}
