"""HAND-EXTRACTED claims. This file IS the extraction record.

EXTRACTION RULES, fixed before the first issue was read and held throughout:

  R1. Extract every assertion the reporter makes ABOUT THE SOFTWARE.
  R2. Include IMPERATIVES and PROPOSALS. The census has DIRECTIVE and
      COMMISSIVE classes; filtering them here would bias axis 1.
  R3. INCLUDE VAGUE CLAIMS. "Not available." "It's slow." These are the
      UNDERDETERMINED class and excluding them is the third selection effect.
      If the thought "this is too vague to check" occurs, that is the
      FORBIDDEN judgement -- extract it anyway.
  R4. EXCLUDE only: pasted program output, stack traces, code blocks, version
      dumps, checkbox boilerplate, and the reporter's meta-commentary about
      their own report. These are the three categories the regex could not
      distinguish; distinguishing them is why this pass is by hand.
  R5. CAP 3 per issue. When an issue has claims in more than one section,
      take them ROUND-ROBIN ACROSS SECTIONS in section order -- NOT the first
      three in document order. Document order would systematically favour
      "Issue Description" over "Expected Behavior" because the template puts
      it first, and "Expected Behavior" is where the normative claims live.
  R6. `why` records why it was included AS A CLAIM. It never records whether
      the claim is checkable -- that is the classification and it happens
      later, against a frozen corpus.
  R7. An issue may yield ZERO claims. Recorded, not skipped.

NO CLASSIFICATION APPEARS IN THIS FILE. Written before any classification code
existed. Zero credits; no API call -- issues_raw.json was already fetched.
"""

# (issue_key, verbatim_text, why_it_is_a_claim)
CLAIMS: list[tuple[str, str, str]] = [
    # ---------------- batch 1 ----------------
    ("pandas#66089",
     "On pandas 3.0.4 + Python 3.14, pd.date_range(..., freq=\"h\") raises an OverflowError / OutOfBoundsTimedelta.",
     "reporter states an observed failure"),
    ("pandas#66089",
     "pd.date_range(\"2026-04-17 00:00\", periods=24, freq=\"h\") should return a DatetimeIndex of 24 hourly timestamps, as it does on pandas 3.0.3.",
     "reporter states the required behaviour"),
    ("pandas#66089",
     "The freq argument is silently reinterpreted as an astronomically large Hours offset instead of <1 * Hours>.",
     "reporter states the mechanism"),

    ("scikit-learn#34278",
     "scikit-learn should start publishing Pyodide/WASM wheels, i.e., with the pyemscripten platform tag as per the accepted and implemented PEP 783, to PyPI, for both ABIs that we currently support.",
     "reporter proposes a required action"),
    ("scikit-learn#34278",
     "This follows on from the RFC for Pyodide being regarded as a somewhat officially supported platform, and resolved as of June 2025.",
     "reporter asserts a historical fact about the project"),
    ("scikit-learn#34278",
     "The rationale to build this case is also Pyodide's ever-growing maturity and stability as a platform.",
     "reporter asserts a property of a dependency"),

    ("pandas#65871",
     "With matplotlib 3.11.0, the default property cycle now returns colors as RGB tuples rather than hex strings.",
     "reporter asserts an upstream behaviour change"),
    ("pandas#65871",
     "This causes 5 pandas plotting tests to fail.",
     "reporter asserts a causal consequence"),
    ("pandas#65871",
     "The upstream matplotlib change is PR 29469 (\"Separate property cycle handling from _process_plot_var_args\"), merged in commit ec65514 and released as part of matplotlib 3.11.0.",
     "reporter asserts the provenance of the change"),

    ("pandas#66434",
     "Supposed to be here https://pandas.pydata.org/docs/whatsnew/v3.0.5.html",
     "reporter asserts where the documentation should be"),
    ("pandas#66434",
     "Not available",
     "reporter asserts the documentation is missing -- VAGUE, deliberately kept (R3)"),
    ("pandas#66434",
     "Please make it available.",
     "reporter directs that it be fixed"),

    ("pandas#66050",
     "When passing a numpy.ma.MaskedArray to pd.array(), the mask is silently ignored and masked (missing) values are not preserved in the resulting pandas array.",
     "reporter states observed wrong behaviour"),
    ("pandas#66050",
     "When converting a NumPy masked array using pd.array(), any masked entries should be converted to the appropriate pandas missing value (pd.NA or np.nan), preserving the mask information faithfully.",
     "reporter states the required behaviour"),
    ("pandas#66050",
     "This leads to incorrect data without any warning or error.",
     "reporter asserts the consequence"),

    ("scikit-learn#34072",
     "Free-threading's lack of GIL makes thread safety issues more likely than in the past.",
     "reporter asserts a causal property of the platform"),
    ("scikit-learn#34072",
     "Switching from a process pool to a thread pool introduces thread-safety issues with the inputs to a Parallel() operation: whereas mutating in a process is fine, mutating in a thread can affect other threads.",
     "reporter asserts a mechanism"),
    ("scikit-learn#34072",
     "The inputs to a Parallel() operation that can correctly run with both process and thread pools should not change when the function is run.",
     "reporter proposes an invariant"),

    ("scikit-learn#33963",
     "Practitioners in safety-critical fields require a method to explicitly quantify the \"Indecision Zone\" of a binary classifier.",
     "reporter asserts a user need"),
    ("scikit-learn#33963",
     "While aggregate metrics like the F1-score or Area Under the ROC Curve provide a high-level view of model performance, they often mask the specific regions where a model's prediction is statistically equivalent to guessing.",
     "reporter asserts a limitation of existing metrics"),
    ("scikit-learn#33963",
     "By implementing the ambiguity_range_score, we enable a Tri-Modal Decision Workflow.",
     "reporter asserts what the proposal would enable"),

    # scikit-learn#34017 -> ZERO CLAIMS: body is a bare CI link plus the
    # standing "not yet ready for a PR" boilerplate. Recorded, not skipped (R7).
]

CLAIMS += [
    # ---------------- batch 2 ----------------
    ("scikit-learn#34483",
     "In most array API estimator methods that happen after .fit(), if an incompatible input is passed to the method, it throws an informative error message, usually coming from check_same_namespace.",
     "reporter asserts the normal behaviour"),
    ("scikit-learn#34483",
     "ValueError with a similar message as the one thrown by Ridge.",
     "reporter states the required result"),
    ("scikit-learn#34483",
     "But PCA's methods like inverse_transform do not use that utility function, erroring out with a less informative message instead, and with the error type being TypeError.",
     "reporter asserts the deviation"),

    ("scikit-learn#33758",
     "In the rendered doc, when the HTML repr of an estimator is too wide, it's just cropped on firefox.",
     "reporter asserts an observed rendering defect"),
    ("scikit-learn#33758",
     "And there's no way to move it or something.",
     "reporter asserts absence of a workaround -- VAGUE (\"or something\"), kept (R3)"),
    ("scikit-learn#33758",
     "I would expect either an horizontal scrollbar or to be able to drag it around.",
     "reporter states the expected behaviour"),

    ("pandas#66347",
     "The tokenize_bytes function currently has a cognitive complexity score of 551 according to clang-tidy, which significantly exceeds the default threshold of 25.",
     "reporter asserts a measured property"),
    ("pandas#66347",
     "The complexity primarily comes from managing 16 distinct parser states within a single monolithic loop, combined with inline SIMD preprocessing and scalar fallback logic.",
     "reporter asserts the cause"),
    ("pandas#66347",
     "Modularizing the state handling into smaller helper functions would help improve the readability and long-term maintainability of the CSV parser.",
     "reporter asserts a proposed benefit"),

    # pandas#65911 -> ZERO CLAIMS: body is a bare link to a PR comment.

    ("scikit-learn#34067",
     "There is a pre-commit hook which will error out if it detects a linting issue.",
     "reporter asserts existing behaviour"),
    ("scikit-learn#34067",
     "Would be ideal if it could also auto-format the offending files beyond just pointing out the error.",
     "reporter proposes desired behaviour"),

    ("pandas#65737",
     "In doc/source/user_guide/visualization.rst, under the \"Automatic date tick adjustment\" section, there is a link pinned to matplotlib v2.0.2.",
     "reporter asserts a fact about the documentation"),
    ("pandas#65737",
     "This page is outdated.",
     "reporter asserts a property -- VAGUE, kept (R3)"),
    ("pandas#65737",
     "The fix is to replace the hardcoded version URL with the newer, stable API reference link.",
     "reporter proposes the fix"),

    ("scikit-learn#33783",
     "We may consider to add a mechanism to re-set the max_subtasks on CallbackContext, so that progress bars can be re-scaled when new information on the maximum number of sub-tasks is available.",
     "reporter proposes a change"),
    ("scikit-learn#33783",
     "Currently, setting the max_subtasks after creating a new subcontext, we'd not be sure if this would update the total on a ProgressBar.",
     "reporter asserts present uncertainty about behaviour"),

    ("scikit-learn#33907",
     "The supported dtype can sometimes vary even if the device name is the same, and we need to do runtime inspection for instance using __array_namespace_info__.dtypes.",
     "reporter asserts a platform fact"),
    ("scikit-learn#33907",
     "We would need to update all the array API test to pass both device and dtype_name to _array_api_for_tests to do this check and raise SkipTest when appropriate instead of running a test that will fail with a low level error message.",
     "reporter states required work"),
    ("scikit-learn#33907",
     "This is the case for PyTorch with the XPU device on different kinds of hardware: some Intel GPUs reachable via this device do support the xp.float64 dtype while others don't.",
     "reporter asserts a specific hardware fact"),

    ("scikit-learn#34356",
     "With v0.15.18, ruff introduces more rules.",
     "reporter asserts an upstream change"),
    ("scikit-learn#34356",
     "Same with Cython-lint v0.16.",
     "reporter asserts the same for another tool"),

    ("pandas#65652",
     "We actually noticed the slowness from pandas.read_sql, but narrowed the problem down to its call to has_table.",
     "reporter asserts an observed performance problem -- \"slowness\" VAGUE, kept (R3)"),
    ("pandas#65652",
     "The problem sees to be in pandas.io.sql.ADBCDatabase.has_table, which calls self.con.adbc_get_objects() without passing depth=.",
     "reporter asserts the mechanism"),
    ("pandas#65652",
     "Adding depth=\"tables\" speeds things up dramatically for us - from 53 seconds without depth=\"tables\" down to 3 seconds with.",
     "reporter asserts a measured improvement"),
]

CLAIMS += [
    # ---------------- batch 3 ----------------
    ("scikit-learn#34569",
     "CI is still failing on Wheel builder (Aug 07, 2026)",
     "reporter asserts an observed CI failure"),

    ("scikit-learn#33958",
     "#31127 was merged and so we can now rely on narwhals.",
     "reporter asserts a state change in the project"),
    ("scikit-learn#33958",
     "NW simplifies internal code by treating all dataframes (pandas, polars, arrow) with a unified API",
     "reporter asserts a benefit"),
    ("scikit-learn#33958",
     "NW can make code faster: for categorical feature support in OrdinalEncoder and other places",
     "reporter asserts a performance benefit"),

    ("pandas#66474",
     "When writing and reading a DF from Excel the the named index is lost for flat indices.",
     "reporter asserts observed data loss"),
    ("pandas#66474",
     "Add a flag or ability to specify index name is present.",
     "reporter proposes a feature"),
    ("pandas#66474",
     "Do nothing.",
     "reporter states an alternative course of action -- MAXIMALLY VAGUE, kept (R3)"),

    ("pandas#66377",
     "In the 1st and the 2nd cases the \"intersection\" goes to the _index_ names.",
     "reporter asserts observed behaviour"),
    ("pandas#66377",
     "In the 3rd and the 4th cases the \"intersection\" goes to the _columns_ names.",
     "reporter asserts observed behaviour, second case"),
    ("pandas#66377",
     "In the 4th case only a _part_ of the \"intersection\" goes to the _columns_ names.",
     "reporter asserts observed behaviour, third case"),
    # NOTE, EXCLUDED AND DISCLOSED: this issue's "Expected Behavior" field reads
    # "Don't know." That is an EPISTEMIC statement about the REPORTER, not an
    # assertion about the software, so R1 excludes it. Recorded here because
    # keeping it would have MANUFACTURED an UNDERDETERMINED instance -- the
    # exact class this route is trying to measure -- out of a reporter's
    # uncertainty rather than a claim's underspecification.

    ("scikit-learn#34315",
     "found a small index error in the docstring for sklearn.metrics.pairwise.paired_manhattan_distances.",
     "reporter asserts a documentation defect"),
    ("scikit-learn#34315",
     "Because Python starts counting at 0, the last item in an array of size n_samples is actually at n_samples - 1.",
     "reporter asserts a general fact used as the premise"),
    ("scikit-learn#34315",
     "To fix this, we just need to update the docstring in sklearn/metrics/pairwise.py to end with (X[n_samples - 1], Y[n_samples - 1]).",
     "reporter proposes the fix"),

    ("pandas#65987",
     "The project would benefit from structured logging to make it easier to debug issues in production.",
     "reporter asserts a benefit"),
    ("pandas#65987",
     "Currently it can be difficult to understand what the application is doing at runtime without adding print statements.",
     "reporter asserts a current limitation -- VAGUE, kept (R3)"),
    ("pandas#65987",
     "Low risk change with high value for users running this in production environments.",
     "reporter asserts risk and value -- VAGUE, kept (R3)"),

    ("pandas#66571",
     "Partial-string slicing on a PeriodIndex whose frequency is anchored to a month that does not line up with calendar quarters resolves the string bounds one period too early, so the slice is shifted and includes an extra label at the start.",
     "reporter asserts precise wrong behaviour"),
    ("pandas#66571",
     "Q-DEC and Q-MAR are correct because their quarters coincide with calendar quarters.",
     "reporter asserts the boundary of the defect"),
    ("pandas#66571",
     "The cause is in PeriodIndex._parsed_string_to_bounds: the string is first parsed with the index frequency, which correctly applies the anchor, but the result is then re-bucketed into a calendar period before being converted back, which discards the anchor.",
     "reporter asserts the mechanism"),

    ("pandas#65740",
     "This found a bug in pandas that did not exist in pandas 2.1.x",
     "reporter asserts a regression"),
    ("pandas#65740",
     "The result is wrong",
     "reporter asserts wrongness with no referent fixed -- VAGUE, kept (R3)"),
    ("pandas#65740",
     "The result should have the correct type and no extra row",
     "reporter states the required behaviour"),

    ("pandas#65730",
     "i think we should implement zizmor in our workflow",
     "reporter proposes an action"),

    ("pandas#65735",
     "In a.map(b), when both a and b are Series and b's dtype is non-nullable, Pandas dynamically changes the output dtype if it can't match all the keys.",
     "reporter asserts existing behaviour"),
    ("pandas#65735",
     "This behaviour changed in the nightlies vs. 3.0; however I am seeing inconsistencies which make little sense to me.",
     "reporter asserts a change plus an inconsistency -- VAGUE, kept (R3)"),
    ("pandas#65735",
     "IMHO there should be no difference in output in the three use cases.",
     "reporter states the required behaviour"),

    ("scikit-learn#34481",
     "CI failed on Unit tests Linux x86-64 ubuntu_atlas (Jul 15, 2026)",
     "reporter asserts a CI failure"),

    ("scikit-learn#34175",
     "Since a tree can be simultaneously used from multiple threads, the statistics will be garbage, as the numbers will get overwritten by different threads.",
     "reporter asserts a concurrency defect"),
    ("scikit-learn#34175",
     "It's possible that this will slow down operation as the same memory needs to be pushed between caches across CPU cores.",
     "reporter asserts a possible performance consequence -- hedged, kept (R3)"),
]

CLAIMS += [
    # ---------------- batch 4 ----------------
    ("pandas#65676",
     "df.eval(\"new=old\", inplace=True) was bypassing CoW protections.",
     "reporter asserts a defect"),
    ("pandas#65676",
     "Because the data took a detour through the external computation engine, the CoW reference tracking metadata was stripped.",
     "reporter asserts the mechanism"),
    ("pandas#65676",
     "The DataFrame assumed the returned array was unshared memory, leading to silent memory corruption when the alias was later modified.",
     "reporter asserts the consequence"),

    ("scikit-learn#33760",
     "MLPClassifier with early_stopping=True raises a TypeError when target labels are strings.",
     "reporter asserts an observed failure"),
    ("scikit-learn#33760",
     "MLPClassifier should handle string labels with early_stopping=True, just as it does with early_stopping=False.",
     "reporter states the required behaviour"),
    ("scikit-learn#33760",
     "The issue is specifically the combination of early_stopping=True + string labels.",
     "reporter asserts the precise trigger"),

    ("scikit-learn#34550",
     "CI failed on Unit tests Linux x86-64 pymin_conda_forge_openblas_ubuntu_2204 (Jul 23, 2026)",
     "reporter asserts a CI failure"),

    ("pandas#66356",
     "There are three python api call patterns that ujson objToJson doesn't reliably check the result code for.",
     "reporter asserts a defect class"),
    ("pandas#66356",
     "All of these are unusual/obscure cases, and apart from the massive int case, are not exercisable just by processing 'untrusted' data.",
     "reporter asserts scope and severity"),
    ("pandas#66356",
     "No crashes/segfaults.",
     "reporter states the required behaviour -- TERSE, kept (R3)"),

    ("scikit-learn#33885",
     "LogisticRegressionCV(use_legacy_attributes=False, refit=False) errors.",
     "reporter asserts an observed failure"),
    ("scikit-learn#33885",
     "no error",
     "reporter states the required result -- MAXIMALLY TERSE, kept (R3)"),

    ("scikit-learn#34641",
     "In the controlling pitfalls page, in section 12.3, there is a recommendation summary for controlling randomness.",
     "reporter asserts a fact about the documentation"),
    ("scikit-learn#34641",
     "I feel that while the note is okay, it makes sense to keep something simple to improve readability for beginners who need an easy reference to look at.",
     "reporter asserts a judgement about documentation quality -- VAGUE, kept (R3)"),
    ("scikit-learn#34641",
     "Add a table to the recommendation summary section, below the paragraph.",
     "reporter proposes a change"),

    ("scikit-learn#34140",
     "In lots of other libraries like XGBoost and LightGBM, callbacks are passed as input parameters to model objects.",
     "reporter asserts an external fact"),
    ("scikit-learn#34140",
     "But in scikit-learn, callbacks need to be kept referenced outside of the object, which is less convenient.",
     "reporter asserts a limitation -- \"less convenient\" VAGUE, kept (R3)"),

    ("pandas#66372",
     "No errors.",
     "reporter states the required behaviour -- TERSE, kept (R3)"),

    ("scikit-learn#33939",
     "CI failed on Unit tests Linux x86-64 pylatest_pip_scipy_dev (May 07, 2026)",
     "reporter asserts a CI failure"),

    ("scikit-learn#34661",
     "sklearn.datasets.dump_svmlight_file terminates the Python interpreter with a segmentation fault when multilabel=True is combined with a one-dimensional target array.",
     "reporter asserts a crash"),
    ("scikit-learn#34661",
     "The input passes the public API parameter validation because y is array-like and multilabel is a boolean.",
     "reporter asserts why validation misses it"),
    ("scikit-learn#34661",
     "A public scikit-learn API should reject it with a clear TypeError or ValueError. It should never terminate the entire Python process.",
     "reporter states the required behaviour"),

    ("scikit-learn#34230",
     "Once fit tasks are completed, the progress bars display 0:00:00 for tasks that last less than a second, which is quite common in practice.",
     "reporter asserts an observed display defect"),
    ("scikit-learn#34230",
     "I think we should display milliseconds and maybe drop the leading 0: for hours, since we almost never do fit tasks that last hours.",
     "reporter proposes a change"),
    ("scikit-learn#34230",
     "if a fit task last 10 ms, we could display 0:00:00.010 or 00:00.010 for instance.",
     "reporter proposes a concrete format"),

    ("pandas#66379",
     "There is a missing backslash in the halflife argument causing the renderer to through a warning.",
     "reporter asserts a defect"),
    ("pandas#66379",
     "It happens only for the dev, the 3.0 docs are correctly formatted.",
     "reporter asserts the scope"),
    ("pandas#66379",
     "Reformat the math section in halflife so that it renders correctly.",
     "reporter proposes the fix"),

    ("scikit-learn#33658",
     "Currently, the n_bins parameter in sklearn.calibration.calibration_curve defaults to 5.",
     "reporter asserts an existing default"),
    ("scikit-learn#33658",
     "This is often suboptimal for datasets of varying sizes, especially for large datasets.",
     "reporter asserts a quality judgement -- VAGUE, kept (R3)"),
    ("scikit-learn#33658",
     "for a dataset of size n = 100,000, the optimal number of bins is on the order of 100, far exceeding the default 5.",
     "reporter asserts a quantitative claim"),

    ("pandas#66378",
     "Rows above min(header) are _ignored_.",
     "reporter asserts observed behaviour"),
    ("pandas#66378",
     "Columns before min(index_col) are _ignored_.",
     "reporter asserts observed behaviour, second case"),
    ("pandas#66378",
     "Can't see it documented.",
     "reporter asserts absence from documentation -- VAGUE, kept (R3)"),
    # NOTE: this issue's "Expected Behavior" is also "Don't know." -- excluded
    # for the same R1 reason recorded at pandas#66377, applied consistently.
]

CLAIMS += [
    # ---------------- batch 5 ----------------
    ("pandas#66368",
     "Calling .str.split() with no separator on an ArrowDtype string column returns extra empty strings when values have leading or trailing whitespace, unlike Python's str.split() or the other pandas backends.",
     "reporter asserts observed wrong behaviour"),
    ("pandas#66368",
     "It happens because the Arrow implementation calls pyarrow's utf8_split_whitespace directly, which doesn't drop those empty pieces the way str.split() does.",
     "reporter asserts the mechanism"),
    ("pandas#66368",
     ".str.split() with no separator should match Python's str.split(), giving [['hi', 'there'], []]",
     "reporter states the required behaviour"),

    ("scikit-learn#33986",
     "For the CPU implementation chunking is already supported. For the array API path we currently perform no chunking.",
     "reporter asserts the existing state"),
    ("scikit-learn#33986",
     "Bigger chunks are better for GPU devices (in terms of execution time), but they require more memory.",
     "reporter asserts a tradeoff"),
    ("scikit-learn#33986",
     "With n_features=20_000 you'd use something like 1.6GB of extra memory without blocking.",
     "reporter asserts a quantitative estimate"),

    ("pandas#66517",
     "Series construction correctly infers object for an integer that no NumPy/nullable integer dtype can hold, but convert_dtypes then tries to force that column to Int64 regardless, and overflows.",
     "reporter asserts observed wrong behaviour"),
    ("pandas#66517",
     "lib.infer_dtype reports \"integer\" for these values, and the object-block conversion maps that straight to Int64 without checking that the values actually fit.",
     "reporter asserts the mechanism"),
    ("pandas#66517",
     "Note this is a plain OverflowError escaping a public API rather than a pandas error type, so it is also not catchable via anything in pandas.errors.",
     "reporter asserts the consequence"),

    ("scikit-learn#34580",
     "Here I propose to require contributors to write comments, PR descriptions and issues using their own words, as opposed to posting AI generated text.",
     "reporter proposes a policy"),
    ("scikit-learn#34580",
     "Using AI to post long generated summaries on issues and PR descriptions and to comment on how to resolve a certain problem is very impolite / disrespectful anyway.",
     "reporter asserts a normative judgement about conduct"),
    ("scikit-learn#34580",
     "It puts the burden on filtering out the useful information (if any) on the reader.",
     "reporter asserts a consequence"),

    ("scikit-learn#33870",
     "When calling array API utilities such as get_namespace, device, etc. on DPNP GPU arrays, it returns incorrect namespaces and devices.",
     "reporter asserts observed wrong behaviour"),
    ("scikit-learn#33870",
     "Note that these objects have all the necessary info specified by the array API standard.",
     "reporter asserts the premise"),
    ("scikit-learn#33870",
     "(dpnp, False, \"gpu:0\")",
     "reporter states the required result as a literal value"),

    ("scikit-learn#34232",
     "PR 34187 sped up multi-threaded operations by using a thread-local, but slowed down single-threaded operations.",
     "reporter asserts a measured tradeoff"),
    ("scikit-learn#34232",
     "This suggests the amount of new work involved is meaningful, and slowing down multi-threaded operations as well.",
     "reporter asserts an inference -- VAGUE, kept (R3)"),
    ("scikit-learn#34232",
     "It's not clear if anyone actually uses these stats (BallTree.get_tree_stats(), BallTree.get_n_calls()), so deprecating it seems like one option.",
     "reporter proposes an action under stated uncertainty"),

    ("scikit-learn#34459",
     "When using LogisticRegression with warm_start=True, the n_iter_ attribute reports [0] on subsequent fits if the model has already converged.",
     "reporter asserts observed behaviour"),
    ("scikit-learn#34459",
     "This is technically correct - lbfgs needs 0 iterations when starting from an already-optimal point - but it is surprising and undocumented.",
     "reporter asserts a judgement -- \"surprising\" VAGUE, kept (R3)"),
    ("scikit-learn#34459",
     "Add a note to the n_iter_ attribute docstring mentioning that n_iter_ can be 0 when warm_start=True and the model has already converged from a previous fit.",
     "reporter proposes the fix"),

    ("pandas#65917",
     "I built ChartScanAI, a free open-source tool that uses AI to analyze financial charts.",
     "reporter asserts a fact about EXTERNAL software -- off-topic promotion, kept: excluding it would be a relevance judgement"),
    ("pandas#65917",
     "This could be useful for traders who want AI-powered chart analysis.",
     "reporter asserts usefulness -- VAGUE, kept (R3)"),

    ("pandas#66266",
     "The value passed to __getitem__ on the last line here is (\"A\", \"B\"), which is currently being treated the same way a list would.",
     "reporter asserts observed behaviour"),
    ("pandas#66266",
     "This should instead be treated as accessing a MultiIndex with levels \"A\" and \"B\" (which does not exist here, raising a KeyError instead).",
     "reporter states the required behaviour"),

    ("scikit-learn#34431",
     "Currently, DecisionBoundaryDisplay.from_estimator does not allow users to control whether decision boundaries are drawn or to customize their line style.",
     "reporter asserts a limitation"),
    ("scikit-learn#34431",
     "Although users can customize the surface through **kwargs, passing parameters such as linewidth or color to style the boundary may instead affect the surface and lead to unexpected behavior.",
     "reporter asserts wrong behaviour -- \"unexpected\" VAGUE, kept (R3)"),
    ("scikit-learn#34431",
     "This API would provide separate and more explicit control over the response surface and the class boundaries, including their colors and other plotting properties.",
     "reporter asserts a proposed benefit"),

    ("pandas#66523",
     "times that are equally spaced should be equivalent to not passing times at all - that invariant is asserted directly by test_ewma_with_times_equal_spacing.",
     "reporter asserts an invariant"),
    ("pandas#66523",
     "It holds for three of the four adjust x ignore_na combinations, but breaks for adjust=False, ignore_na=False once the data contains NaN.",
     "reporter asserts the observed defect"),
    ("pandas#66523",
     "The two paths generalize adjust=False to a gap of delta differently. They agree at delta = 1 and diverge otherwise.",
     "reporter asserts the mechanism"),

    ("pandas#66054",
     "Creating a DataFrame from an existing Series or Index does not always respect Copy-on-Write semantics.",
     "reporter asserts observed wrong behaviour"),
    ("pandas#66054",
     "In some cases, modifying the resulting DataFrame can unexpectedly modify the original object.",
     "reporter asserts the consequence -- \"some cases\" VAGUE, kept (R3)"),
    ("pandas#66054",
     "Changes made to the DataFrame should not affect the original Series or Index.",
     "reporter states the required behaviour"),

    ("pandas#66616",
     "The \"Getitem ([])\" section of the \"10 minutes to pandas\" tutorial shows that a single label in brackets will return a Series.",
     "reporter asserts a fact about the documentation"),
    ("pandas#66616",
     "It never shows the specific case of a list containing a single label (e.g. df[[\"A\"]], which also returns a DataFrame).",
     "reporter asserts a documentation gap"),
    ("pandas#66616",
     "since df[\"A\"] and df[[\"A\"]] look nearly identical but return different object types, this could be a common point of confusion for beginners",
     "reporter asserts a judgement -- VAGUE, kept (R3)"),

    ("scikit-learn#34076",
     "Whenever an array-like of string types for a multi-class classification problem is passed into the confusion_matrix function without an argument passed for labels, the confusion matrix is returned with the classes in alphabetical order.",
     "reporter asserts existing behaviour"),
    ("scikit-learn#34076",
     "the outputted confusion matrix may have an output order that is different from the user's expectations, especially if the classes are ordinal",
     "reporter asserts a consequence -- VAGUE, kept (R3)"),
    ("scikit-learn#34076",
     "There is currently no warning for this, possibly leading to misunderstood confusions matrices by users.",
     "reporter asserts a gap and its consequence"),
]

CLAIMS += [
    # ---------------- batch 6 ----------------
    ("scikit-learn#34566",
     "CI failed on Unit tests Linux x86-64 pymin_conda_forge_openblas_min_dependencies (Jul 25, 2026)",
     "reporter asserts a CI failure"),

    ("scikit-learn#34086",
     "In line 530, sklearn/svm/src/libsvm/svm.cpp, it is said \"An SMO algorithm in Fan et al., JMLR 6(2005), p. 1889--1918\", but this paper does not appear in the page of the main author.",
     "reporter asserts a citation defect"),
    ("scikit-learn#34086",
     "I noticed that the pages, publishing year and issues are just the same to another work: Fan RE, Chen PH, Lin CJ, Working set selection using second order information.",
     "reporter asserts the identity of the real source"),
    ("scikit-learn#34086",
     "use the correct and full information of the article",
     "reporter proposes the fix -- VAGUE, kept (R3)"),

    ("pandas#66281",
     "Invoking .apply() with custom Python functions is notoriously slow in Pandas because it loops over rows in pure Python.",
     "reporter asserts a performance property -- \"notoriously slow\" VAGUE, kept (R3)"),
    ("pandas#66281",
     "While Pandas supports Numba engines in GroupBy and Rolling window methods, standard .apply() lacks direct JIT compilation engines.",
     "reporter asserts a capability gap"),
    ("pandas#66281",
     "Introduce a JIT compilation execution engine option inside Series.apply(), supporting engine=\"numba\" and engine_kwargs parameters.",
     "reporter proposes a feature"),

    ("pandas#66542",
     "the fix is a two-line validation at the top of to_datetime, mirroring to_timedelta.",
     "reporter proposes the fix"),

    ("pandas#66509",
     "Passing self_destruct=True through to_pandas_kwargs segfaults the interpreter.",
     "reporter asserts a crash"),
    ("pandas#66509",
     "to_pandas_kwargs is 3.0 only. On 2.3.3 the argument falls through to pyarrow.parquet.read_table and raises TypeError, so this looks specific to the 3.0 passthrough.",
     "reporter asserts the scope"),
    ("pandas#66509",
     "So the trigger is self_destruct, and there is nothing wrong with the passthrough itself. I get the same results on macOS/arm64 and Linux/x86-64.",
     "reporter asserts the isolated trigger and its portability"),

    ("scikit-learn#34311",
     "We should make the array API dispatch flag explicit in tests that compare dispatch Off and On.",
     "reporter proposes a change"),
    ("scikit-learn#34311",
     "Right now we have tests that assume that the default setting of the flag is off when computing the reference values.",
     "reporter asserts the existing state"),
    ("scikit-learn#34311",
     "I'm not sure if this is a problem or will lead to false results in our tests. But it seems like a good idea to make the setting explicit in our tests.",
     "reporter asserts a judgement under stated uncertainty -- VAGUE, kept (R3)"),

    ("scikit-learn#34075",
     "In nilearn we have started using the HTML representation of estimators in the report we generate.",
     "reporter asserts a downstream usage"),
    ("scikit-learn#34075",
     "However when testing with 1.9.0rc1 I am now getting this error.",
     "reporter asserts a regression"),
    ("scikit-learn#34075",
     "My hunch would be to be able to define an optional list of attributes to skip in html representation.",
     "reporter proposes a solution -- hedged, kept (R3)"),

    ("scikit-learn#34082",
     "in preparing the design matrix with StandardScaler we're seeing some unfortunate floating point deviations between MacOS ARM and x86_64 Linux platforms.",
     "reporter asserts a cross-platform numerical deviation"),
    ("scikit-learn#34082",
     "the differences are somewhat subtle, they are leading to downstream estimator scoring deviations that are perhaps not quite in the noise (accuracy score differences on the order of 0.0001).",
     "reporter asserts the magnitude -- hedged, kept (R3)"),
    ("scikit-learn#34082",
     "We did check that if we serialize the design matrices on one platform and fit the estimator on those identical NumPy arrays on the other platform then the estimators perform identically on each platform as expected.",
     "reporter asserts a control experiment"),

    ("scikit-learn#33800",
     "The current workflow requires manually computing separate confusion matrices and subtracting them.",
     "reporter asserts the existing workflow"),
    ("scikit-learn#33800",
     "This pattern has no built-in support in sklearn and becomes error-prone when normalization is involved - normalizing before vs after subtraction gives different results.",
     "reporter asserts a gap and a hazard"),
    ("scikit-learn#33800",
     "Add confusion_matrix_diff to sklearn.metrics.",
     "reporter proposes a feature"),

    ("scikit-learn#34312",
     "if the uncalibrated classifier only exposes a decision_function and no predict_proba our implementation of sigmoid calibration is fine because the output values of decision_function are morally logits between -inf and +inf with 0 as the default decision threshold.",
     "reporter asserts where the implementation is correct"),
    ("scikit-learn#34312",
     "But if the uncalibrated classifier already exposes a predict_proba method, our current implementation takes the predicted probabilities as input of the parametrized sigmoid function. This is incorrect.",
     "reporter asserts the defect"),

    ("pandas#65770",
     "pd.testing.assert_series_equal fails when comparing two equal Series objects if one is backed by a plain np.ndarray and the other by an np.ndarray subclass, even when check_series_type=False is passed.",
     "reporter asserts observed wrong behaviour"),
    ("pandas#65770",
     "The error message is also misleading: it reports \"Series classes are different\", but the classes shown are the backing array classes, not the Series classes.",
     "reporter asserts a second defect in the message"),
    ("pandas#65770",
     "The assertion should pass, since both objects are equal.",
     "reporter states the required behaviour"),

    ("scikit-learn#34045",
     "Triage / fix / review issues and PR milestoned for 1.9 and then follow the release process.",
     "reporter directs a course of work"),

    ("pandas#66400",
     "My guess is that because these are such large integers, there is precision loss during the execution of the compiled C/Cython, possibly from casting to float64 types.",
     "reporter asserts a hypothesised mechanism -- hedged, kept (R3)"),
    ("pandas#66400",
     "The atol should be respected such that no AssertionError is raised by the code snippet.",
     "reporter states the required behaviour"),

    ("scikit-learn#33838",
     "CI failed on Unit tests Windows x64 pymin_conda_forge_openblas (Apr 23, 2026)",
     "reporter asserts a CI failure"),
    ("scikit-learn#33838",
     "Unable to find junit file.",
     "reporter asserts a missing artifact -- TERSE, kept (R3)"),
]

CLAIMS += [
    # ---------------- batch 7 (final; >=200 target met) ----------------
    ("scikit-learn#33867",
     "It seems that the https://api.openml.org/api/v1 URL used in our code should have been written https://www.openml.org/api/v1 instead.",
     "reporter asserts a configuration defect -- hedged, kept (R3)"),
    ("scikit-learn#33867",
     "No error.",
     "reporter states the required result -- TERSE, kept (R3)"),
    ("scikit-learn#33867",
     "It's breaking the CI and negatively impacting all users of that functions, especially in educational material with runnable code snippets.",
     "reporter asserts the impact"),

    ("pandas#66232",
     "A CHANGELOG.md file would help users understand what changed between versions and make upgrade decisions easier.",
     "reporter asserts a benefit"),
    ("pandas#66232",
     "When upgrading dependencies, developers need to know what bugs were fixed, what new features were added, whether there are any breaking changes.",
     "reporter asserts a user need"),
    ("pandas#66232",
     "This is purely a documentation change with no code impact.",
     "reporter asserts the scope of the change"),

    ("scikit-learn#33742",
     "In LeaveOneOut and LeavePOut classes, the documentation mentions that these methods \"can be very costly\" for large datasets, but the warning is quite vague.",
     "reporter asserts a documentation weakness -- \"quite vague\" VAGUE, kept (R3)"),
    ("scikit-learn#33742",
     "Users often try these on datasets with thousands of samples and face very long runtimes or memory issues without clear guidance on when to avoid them.",
     "reporter asserts a user-behaviour consequence"),
    ("scikit-learn#33742",
     "Add a clearer UserWarning when n_samples is large (e.g., > 1000 for LeaveOneOut).",
     "reporter proposes a change"),

    ("scikit-learn#34200",
     "CI is still failing on Unit tests Linux x86-64 pylatest_free_threaded (Jul 22, 2026)",
     "reporter asserts a CI failure"),

    ("scikit-learn#33746",
     "StratifiedGroupKFold has complex logic in _iter_test_indices and _find_best_fold.",
     "reporter asserts a code property -- \"complex\" VAGUE, kept (R3)"),
    ("scikit-learn#33746",
     "There are several corner cases (e.g. groups with only one sample, very uneven class distributions, or small number of groups) that can lead to unexpected behavior or degenerate splits.",
     "reporter asserts a risk -- \"unexpected\" VAGUE, kept (R3)"),
    ("scikit-learn#33746",
     "Current test coverage for these edge cases is limited.",
     "reporter asserts a coverage gap -- VAGUE, kept (R3)"),

    ("pandas#65903",
     "In pandas/_libs/src/datetime/date_conversions.c, when make_iso_8601_datetime fails, result is freed via PyObject_Free but the function does NOT return.",
     "reporter asserts a precise code defect"),
    ("pandas#65903",
     "Use-after-free: strlen reads freed memory. The freed pointer is returned to the caller, which will read/use corrupted data.",
     "reporter asserts the consequence"),
    ("pandas#65903",
     "Add return NULL; after PyObject_Free(result);",
     "reporter proposes the fix"),

    ("scikit-learn#34537",
     "This was moved from the setuptools days to pyproject.toml, I don't think anyone is using it but I could be wrong of course.",
     "reporter asserts a usage claim -- hedged, kept (R3)"),
    ("scikit-learn#34537",
     "It is definitely not mentioned in the doc, and I would rather remove all the extra_requires unless someone has a strong use case for it.",
     "reporter asserts a documentation gap and proposes removal"),
    ("scikit-learn#34537",
     "They are likely not used by anyone.",
     "reporter asserts a usage claim -- hedged, kept (R3)"),

    ("scikit-learn#34087",
     "Torch offers sparse arrays which, unlike SciPy's objects, are sub-classed from regular dense arrays.",
     "reporter asserts an external library fact"),
    ("scikit-learn#34087",
     "Technically, sparse torch objects are torch tensors, and they appear to (unintendedly?) work under array API dispatch in some cases, but not in every scenario where array API is supported.",
     "reporter asserts inconsistent behaviour -- \"some cases\" VAGUE, kept (R3)"),
    ("scikit-learn#34087",
     "Since torch does not really implement the array API standard and does not implement __array_namespace__ in any object class, it's not possible to make a check like \"is array API\" based on that.",
     "reporter asserts an impossibility"),

    ("pandas#66012",
     "If you build a DataFrame from an Index or Series backed by an Extension Array, CoW reference tracking is missing.",
     "reporter asserts observed wrong behaviour"),
    ("pandas#66012",
     "we ran into IPython kernel crashes when trying to display a DataFrame whose columns had been modified this way, which suggests some internal block manager invariants are getting broken too.",
     "reporter asserts a further symptom -- hedged, kept (R3)"),
    ("pandas#66012",
     "df.columns shouldn't be affected at all. CoW means either copy the data upfront or track the reference and copy on first write - neither is happening here.",
     "reporter states the required behaviour"),

    ("pandas#66203",
     "When calling DataFrame.apply(..., raw=True) with the default Python engine, pandas currently delegates array execution to numpy.apply_along_axis.",
     "reporter asserts the existing implementation"),
    ("pandas#66203",
     "it introduces significant Python-level overhead (dynamic coordinate tuple creation, slice-by-slice writes, first-element inspection to determine dtype).",
     "reporter asserts a performance cause"),
    ("pandas#66203",
     "Since DataFrame values are strictly 2D, we can optimize this execution path by using a fast-path list comprehension and transposition logic, which yields a 1.4x to 2.2x performance improvement.",
     "reporter asserts a quantified improvement"),

    ("scikit-learn#34128",
     "Modern CPUs such as Intel Core Ultra Series 3 processors and Apple M1/M2 series have different core speeds (P-cores, E-cores, LP-cores).",
     "reporter asserts a hardware fact"),
    ("scikit-learn#34128",
     "joblib and native libraries such as OpenMP or BLAS libraries will often start one thread per core.",
     "reporter asserts existing behaviour"),
    ("scikit-learn#34128",
     "thread scheduling overhead can cause performance degradation compared to using fewer threads on those architectures, especially when iterating on many small data problems.",
     "reporter asserts a performance consequence"),

    ("scikit-learn#34401",
     "Typo in _RidgeClassifierMixin.predict: X : {array-like, spare matrix} should be X : {array-like, sparse matrix}.",
     "reporter asserts a precise documentation defect"),
    ("scikit-learn#34401",
     "Extra space in Ridge See Also section: RidgeClassifierCV :  Ridge classifier should be RidgeClassifierCV : Ridge classifier.",
     "reporter asserts a second precise defect"),
    ("scikit-learn#34401",
     "Missing RST function links in RidgeClassifier solver descriptions; Ridge correctly uses RST :func: links for solver references.",
     "reporter asserts a third defect by contrast"),
]
