# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import netd_pb2 as netd__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in netd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """=============================================================================
    NodeService — local node identity & status
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNodeInfo = channel.unary_unary(
                '/netd.NodeService/GetNodeInfo',
                request_serializer=netd__pb2.Empty.SerializeToString,
                response_deserializer=netd__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/netd.NodeService/GetStatus',
                request_serializer=netd__pb2.Empty.SerializeToString,
                response_deserializer=netd__pb2.NodeStatus.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """=============================================================================
    NodeService — local node identity & status
    =============================================================================
    """

    def GetNodeInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=netd__pb2.Empty.FromString,
                    response_serializer=netd__pb2.NodeInfo.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=netd__pb2.Empty.FromString,
                    response_serializer=netd__pb2.NodeStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """=============================================================================
    NodeService — local node identity & status
    =============================================================================
    """

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.NodeService/GetNodeInfo',
            netd__pb2.Empty.SerializeToString,
            netd__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.NodeService/GetStatus',
            netd__pb2.Empty.SerializeToString,
            netd__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DiscoveryServiceStub(object):
    """=============================================================================
    DiscoveryService — find agents by capability
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishAgent = channel.unary_unary(
                '/netd.DiscoveryService/PublishAgent',
                request_serializer=netd__pb2.AgentAdvertisement.SerializeToString,
                response_deserializer=netd__pb2.PublishResult.FromString,
                _registered_method=True)
        self.FindAgents = channel.unary_stream(
                '/netd.DiscoveryService/FindAgents',
                request_serializer=netd__pb2.AgentQuery.SerializeToString,
                response_deserializer=netd__pb2.AgentAdvertisement.FromString,
                _registered_method=True)
        self.UnpublishAgent = channel.unary_unary(
                '/netd.DiscoveryService/UnpublishAgent',
                request_serializer=netd__pb2.UnpublishRequest.SerializeToString,
                response_deserializer=netd__pb2.Empty.FromString,
                _registered_method=True)


class DiscoveryServiceServicer(object):
    """=============================================================================
    DiscoveryService — find agents by capability
    =============================================================================
    """

    def PublishAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnpublishAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscoveryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishAgent,
                    request_deserializer=netd__pb2.AgentAdvertisement.FromString,
                    response_serializer=netd__pb2.PublishResult.SerializeToString,
            ),
            'FindAgents': grpc.unary_stream_rpc_method_handler(
                    servicer.FindAgents,
                    request_deserializer=netd__pb2.AgentQuery.FromString,
                    response_serializer=netd__pb2.AgentAdvertisement.SerializeToString,
            ),
            'UnpublishAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnpublishAgent,
                    request_deserializer=netd__pb2.UnpublishRequest.FromString,
                    response_serializer=netd__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.DiscoveryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.DiscoveryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscoveryService(object):
    """=============================================================================
    DiscoveryService — find agents by capability
    =============================================================================
    """

    @staticmethod
    def PublishAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.DiscoveryService/PublishAgent',
            netd__pb2.AgentAdvertisement.SerializeToString,
            netd__pb2.PublishResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netd.DiscoveryService/FindAgents',
            netd__pb2.AgentQuery.SerializeToString,
            netd__pb2.AgentAdvertisement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnpublishAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.DiscoveryService/UnpublishAgent',
            netd__pb2.UnpublishRequest.SerializeToString,
            netd__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PeerServiceStub(object):
    """=============================================================================
    PeerService — direct peer connections
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/netd.PeerService/Connect',
                request_serializer=netd__pb2.ConnectRequest.SerializeToString,
                response_deserializer=netd__pb2.ConnectResult.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/netd.PeerService/Disconnect',
                request_serializer=netd__pb2.DisconnectRequest.SerializeToString,
                response_deserializer=netd__pb2.Empty.FromString,
                _registered_method=True)
        self.ListPeers = channel.unary_unary(
                '/netd.PeerService/ListPeers',
                request_serializer=netd__pb2.Empty.SerializeToString,
                response_deserializer=netd__pb2.PeerList.FromString,
                _registered_method=True)
        self.GetPeerInfo = channel.unary_unary(
                '/netd.PeerService/GetPeerInfo',
                request_serializer=netd__pb2.PeerInfoRequest.SerializeToString,
                response_deserializer=netd__pb2.PeerInfo.FromString,
                _registered_method=True)


class PeerServiceServicer(object):
    """=============================================================================
    PeerService — direct peer connections
    =============================================================================
    """

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=netd__pb2.ConnectRequest.FromString,
                    response_serializer=netd__pb2.ConnectResult.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=netd__pb2.DisconnectRequest.FromString,
                    response_serializer=netd__pb2.Empty.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=netd__pb2.Empty.FromString,
                    response_serializer=netd__pb2.PeerList.SerializeToString,
            ),
            'GetPeerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerInfo,
                    request_deserializer=netd__pb2.PeerInfoRequest.FromString,
                    response_serializer=netd__pb2.PeerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.PeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.PeerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerService(object):
    """=============================================================================
    PeerService — direct peer connections
    =============================================================================
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.PeerService/Connect',
            netd__pb2.ConnectRequest.SerializeToString,
            netd__pb2.ConnectResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.PeerService/Disconnect',
            netd__pb2.DisconnectRequest.SerializeToString,
            netd__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.PeerService/ListPeers',
            netd__pb2.Empty.SerializeToString,
            netd__pb2.PeerList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.PeerService/GetPeerInfo',
            netd__pb2.PeerInfoRequest.SerializeToString,
            netd__pb2.PeerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """=============================================================================
    MessageService — send arbitrary messages to peers
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/netd.MessageService/Send',
                request_serializer=netd__pb2.SendRequest.SerializeToString,
                response_deserializer=netd__pb2.SendResult.FromString,
                _registered_method=True)
        self.Broadcast = channel.unary_unary(
                '/netd.MessageService/Broadcast',
                request_serializer=netd__pb2.BroadcastRequest.SerializeToString,
                response_deserializer=netd__pb2.BroadcastResult.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/netd.MessageService/Subscribe',
                request_serializer=netd__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=netd__pb2.IncomingMessage.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """=============================================================================
    MessageService — send arbitrary messages to peers
    =============================================================================
    """

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Broadcast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=netd__pb2.SendRequest.FromString,
                    response_serializer=netd__pb2.SendResult.SerializeToString,
            ),
            'Broadcast': grpc.unary_unary_rpc_method_handler(
                    servicer.Broadcast,
                    request_deserializer=netd__pb2.BroadcastRequest.FromString,
                    response_serializer=netd__pb2.BroadcastResult.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=netd__pb2.SubscribeRequest.FromString,
                    response_serializer=netd__pb2.IncomingMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """=============================================================================
    MessageService — send arbitrary messages to peers
    =============================================================================
    """

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.MessageService/Send',
            netd__pb2.SendRequest.SerializeToString,
            netd__pb2.SendResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Broadcast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.MessageService/Broadcast',
            netd__pb2.BroadcastRequest.SerializeToString,
            netd__pb2.BroadcastResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netd.MessageService/Subscribe',
            netd__pb2.SubscribeRequest.SerializeToString,
            netd__pb2.IncomingMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DHTServiceStub(object):
    """=============================================================================
    DHTService — direct DHT operations
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/netd.DHTService/Put',
                request_serializer=netd__pb2.DHTRecord.SerializeToString,
                response_deserializer=netd__pb2.DHTResult.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/netd.DHTService/Get',
                request_serializer=netd__pb2.DHTKey.SerializeToString,
                response_deserializer=netd__pb2.DHTRecord.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/netd.DHTService/Delete',
                request_serializer=netd__pb2.DHTKey.SerializeToString,
                response_deserializer=netd__pb2.DHTResult.FromString,
                _registered_method=True)


class DHTServiceServicer(object):
    """=============================================================================
    DHTService — direct DHT operations
    =============================================================================
    """

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DHTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=netd__pb2.DHTRecord.FromString,
                    response_serializer=netd__pb2.DHTResult.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=netd__pb2.DHTKey.FromString,
                    response_serializer=netd__pb2.DHTRecord.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=netd__pb2.DHTKey.FromString,
                    response_serializer=netd__pb2.DHTResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.DHTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.DHTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DHTService(object):
    """=============================================================================
    DHTService — direct DHT operations
    =============================================================================
    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.DHTService/Put',
            netd__pb2.DHTRecord.SerializeToString,
            netd__pb2.DHTResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.DHTService/Get',
            netd__pb2.DHTKey.SerializeToString,
            netd__pb2.DHTRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.DHTService/Delete',
            netd__pb2.DHTKey.SerializeToString,
            netd__pb2.DHTResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class GossipServiceStub(object):
    """=============================================================================
    GossipService — cross-cluster blackboard delta sync via libp2p
    gossipsub. Each project has its own topic
    /gyza/project/{project_id}/blackboard. Deltas are signed at two
    layers: libp2p pubsub envelope (StrictSignatureVerification) and
    an app-layer Ed25519 signature over BLAKE3(delta_with_sig_zeroed).

    SubscribeDeltas is server-streaming; the daemon pushes deltas to
    every subscriber as they arrive on the project's topic. Multiple
    Python clients on one daemon can subscribe simultaneously without
    stepping on each other — the daemon fans out internally.
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinProject = channel.unary_unary(
                '/netd.GossipService/JoinProject',
                request_serializer=netd__pb2.JoinProjectRequest.SerializeToString,
                response_deserializer=netd__pb2.JoinProjectResult.FromString,
                _registered_method=True)
        self.LeaveProject = channel.unary_unary(
                '/netd.GossipService/LeaveProject',
                request_serializer=netd__pb2.LeaveProjectRequest.SerializeToString,
                response_deserializer=netd__pb2.Empty.FromString,
                _registered_method=True)
        self.PublishDelta = channel.unary_unary(
                '/netd.GossipService/PublishDelta',
                request_serializer=netd__pb2.PublishDeltaRequest.SerializeToString,
                response_deserializer=netd__pb2.PublishDeltaResult.FromString,
                _registered_method=True)
        self.SubscribeDeltas = channel.unary_stream(
                '/netd.GossipService/SubscribeDeltas',
                request_serializer=netd__pb2.SubscribeDeltasRequest.SerializeToString,
                response_deserializer=netd__pb2.BlackboardDelta.FromString,
                _registered_method=True)
        self.ListProjects = channel.unary_unary(
                '/netd.GossipService/ListProjects',
                request_serializer=netd__pb2.Empty.SerializeToString,
                response_deserializer=netd__pb2.ProjectList.FromString,
                _registered_method=True)


class GossipServiceServicer(object):
    """=============================================================================
    GossipService — cross-cluster blackboard delta sync via libp2p
    gossipsub. Each project has its own topic
    /gyza/project/{project_id}/blackboard. Deltas are signed at two
    layers: libp2p pubsub envelope (StrictSignatureVerification) and
    an app-layer Ed25519 signature over BLAKE3(delta_with_sig_zeroed).

    SubscribeDeltas is server-streaming; the daemon pushes deltas to
    every subscriber as they arrive on the project's topic. Multiple
    Python clients on one daemon can subscribe simultaneously without
    stepping on each other — the daemon fans out internally.
    =============================================================================
    """

    def JoinProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeDeltas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GossipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinProject': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinProject,
                    request_deserializer=netd__pb2.JoinProjectRequest.FromString,
                    response_serializer=netd__pb2.JoinProjectResult.SerializeToString,
            ),
            'LeaveProject': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveProject,
                    request_deserializer=netd__pb2.LeaveProjectRequest.FromString,
                    response_serializer=netd__pb2.Empty.SerializeToString,
            ),
            'PublishDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishDelta,
                    request_deserializer=netd__pb2.PublishDeltaRequest.FromString,
                    response_serializer=netd__pb2.PublishDeltaResult.SerializeToString,
            ),
            'SubscribeDeltas': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeDeltas,
                    request_deserializer=netd__pb2.SubscribeDeltasRequest.FromString,
                    response_serializer=netd__pb2.BlackboardDelta.SerializeToString,
            ),
            'ListProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=netd__pb2.Empty.FromString,
                    response_serializer=netd__pb2.ProjectList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.GossipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.GossipService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GossipService(object):
    """=============================================================================
    GossipService — cross-cluster blackboard delta sync via libp2p
    gossipsub. Each project has its own topic
    /gyza/project/{project_id}/blackboard. Deltas are signed at two
    layers: libp2p pubsub envelope (StrictSignatureVerification) and
    an app-layer Ed25519 signature over BLAKE3(delta_with_sig_zeroed).

    SubscribeDeltas is server-streaming; the daemon pushes deltas to
    every subscriber as they arrive on the project's topic. Multiple
    Python clients on one daemon can subscribe simultaneously without
    stepping on each other — the daemon fans out internally.
    =============================================================================
    """

    @staticmethod
    def JoinProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.GossipService/JoinProject',
            netd__pb2.JoinProjectRequest.SerializeToString,
            netd__pb2.JoinProjectResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.GossipService/LeaveProject',
            netd__pb2.LeaveProjectRequest.SerializeToString,
            netd__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.GossipService/PublishDelta',
            netd__pb2.PublishDeltaRequest.SerializeToString,
            netd__pb2.PublishDeltaResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeDeltas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/netd.GossipService/SubscribeDeltas',
            netd__pb2.SubscribeDeltasRequest.SerializeToString,
            netd__pb2.BlackboardDelta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.GossipService/ListProjects',
            netd__pb2.Empty.SerializeToString,
            netd__pb2.ProjectList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CapabilityServiceStub(object):
    """=============================================================================
    CapabilityService — proof-of-capability sybil resistance.

    A new node that wants Tier-3 DHT visibility must demonstrate it can
    actually execute agent tasks. It collects a signed AttestationCert
    from ≥2 of 3 existing Tier-3 validators by:

    1. Each validator issues a Challenge (random task IDs from the
    canonical eval suite, signed nonce, expiry).
    2. The applicant executes the tasks locally and returns
    ChallengeResponse with per-task ICP envelopes (proof of
    execution by the claimed agent).
    3. Each validator verifies the response and co-signs an
    AttestationBody.
    4. The applicant assembles AttestationCert from ≥2 cosignatures
    and publishes it to the DHT at /gyza/attestations/{pubkey}.

    Other nodes that see Tier-3 advertisements check the cert via
    VerifyAttestation before trusting routing/work-claim signals from
    the advertiser.

    All sign/verify steps use proto.MarshalOptions{Deterministic: true}
    over the *Body message so cross-runtime reproduction is exact.
    =============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueChallenge = channel.unary_unary(
                '/netd.CapabilityService/IssueChallenge',
                request_serializer=netd__pb2.IssueChallengeRequest.SerializeToString,
                response_deserializer=netd__pb2.Challenge.FromString,
                _registered_method=True)
        self.VerifyResponse = channel.unary_unary(
                '/netd.CapabilityService/VerifyResponse',
                request_serializer=netd__pb2.VerifyResponseRequest.SerializeToString,
                response_deserializer=netd__pb2.VerifyResponseResult.FromString,
                _registered_method=True)
        self.PublishAttestation = channel.unary_unary(
                '/netd.CapabilityService/PublishAttestation',
                request_serializer=netd__pb2.AttestationCert.SerializeToString,
                response_deserializer=netd__pb2.PublishAttestationResult.FromString,
                _registered_method=True)
        self.FetchAttestation = channel.unary_unary(
                '/netd.CapabilityService/FetchAttestation',
                request_serializer=netd__pb2.FetchAttestationRequest.SerializeToString,
                response_deserializer=netd__pb2.AttestationCert.FromString,
                _registered_method=True)
        self.VerifyAttestation = channel.unary_unary(
                '/netd.CapabilityService/VerifyAttestation',
                request_serializer=netd__pb2.AttestationCert.SerializeToString,
                response_deserializer=netd__pb2.VerifyAttestationResult.FromString,
                _registered_method=True)


class CapabilityServiceServicer(object):
    """=============================================================================
    CapabilityService — proof-of-capability sybil resistance.

    A new node that wants Tier-3 DHT visibility must demonstrate it can
    actually execute agent tasks. It collects a signed AttestationCert
    from ≥2 of 3 existing Tier-3 validators by:

    1. Each validator issues a Challenge (random task IDs from the
    canonical eval suite, signed nonce, expiry).
    2. The applicant executes the tasks locally and returns
    ChallengeResponse with per-task ICP envelopes (proof of
    execution by the claimed agent).
    3. Each validator verifies the response and co-signs an
    AttestationBody.
    4. The applicant assembles AttestationCert from ≥2 cosignatures
    and publishes it to the DHT at /gyza/attestations/{pubkey}.

    Other nodes that see Tier-3 advertisements check the cert via
    VerifyAttestation before trusting routing/work-claim signals from
    the advertiser.

    All sign/verify steps use proto.MarshalOptions{Deterministic: true}
    over the *Body message so cross-runtime reproduction is exact.
    =============================================================================
    """

    def IssueChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishAttestation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAttestation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyAttestation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueChallenge,
                    request_deserializer=netd__pb2.IssueChallengeRequest.FromString,
                    response_serializer=netd__pb2.Challenge.SerializeToString,
            ),
            'VerifyResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyResponse,
                    request_deserializer=netd__pb2.VerifyResponseRequest.FromString,
                    response_serializer=netd__pb2.VerifyResponseResult.SerializeToString,
            ),
            'PublishAttestation': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishAttestation,
                    request_deserializer=netd__pb2.AttestationCert.FromString,
                    response_serializer=netd__pb2.PublishAttestationResult.SerializeToString,
            ),
            'FetchAttestation': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAttestation,
                    request_deserializer=netd__pb2.FetchAttestationRequest.FromString,
                    response_serializer=netd__pb2.AttestationCert.SerializeToString,
            ),
            'VerifyAttestation': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyAttestation,
                    request_deserializer=netd__pb2.AttestationCert.FromString,
                    response_serializer=netd__pb2.VerifyAttestationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'netd.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('netd.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService(object):
    """=============================================================================
    CapabilityService — proof-of-capability sybil resistance.

    A new node that wants Tier-3 DHT visibility must demonstrate it can
    actually execute agent tasks. It collects a signed AttestationCert
    from ≥2 of 3 existing Tier-3 validators by:

    1. Each validator issues a Challenge (random task IDs from the
    canonical eval suite, signed nonce, expiry).
    2. The applicant executes the tasks locally and returns
    ChallengeResponse with per-task ICP envelopes (proof of
    execution by the claimed agent).
    3. Each validator verifies the response and co-signs an
    AttestationBody.
    4. The applicant assembles AttestationCert from ≥2 cosignatures
    and publishes it to the DHT at /gyza/attestations/{pubkey}.

    Other nodes that see Tier-3 advertisements check the cert via
    VerifyAttestation before trusting routing/work-claim signals from
    the advertiser.

    All sign/verify steps use proto.MarshalOptions{Deterministic: true}
    over the *Body message so cross-runtime reproduction is exact.
    =============================================================================
    """

    @staticmethod
    def IssueChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.CapabilityService/IssueChallenge',
            netd__pb2.IssueChallengeRequest.SerializeToString,
            netd__pb2.Challenge.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.CapabilityService/VerifyResponse',
            netd__pb2.VerifyResponseRequest.SerializeToString,
            netd__pb2.VerifyResponseResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishAttestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.CapabilityService/PublishAttestation',
            netd__pb2.AttestationCert.SerializeToString,
            netd__pb2.PublishAttestationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchAttestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.CapabilityService/FetchAttestation',
            netd__pb2.FetchAttestationRequest.SerializeToString,
            netd__pb2.AttestationCert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyAttestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/netd.CapabilityService/VerifyAttestation',
            netd__pb2.AttestationCert.SerializeToString,
            netd__pb2.VerifyAttestationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
