#!/usr/bin/env python3
"""
Regenerate Rust parity-test fixtures for `gyza-rs/gyza-crypto`.

When the Python crypto primitives change (or when we want to add new
parity test vectors), run this script with the marshal venv and paste
the output hex strings into `gyza-rs/gyza-crypto/src/lib.rs`'s test
module.

Usage:
    ~/dev/marshal/.os/bin/python gyza-rs/scripts/regenerate_crypto_fixtures.py

Output: hex strings to paste into the test module.

The master seed used here is a fixed 32-byte test vector (NOT a
real key). Don't use this seed for anything other than test fixture
generation.
"""
from __future__ import annotations

import sys
from pathlib import Path

# Make sure we can import gyza.identity for its _derive_seed.
ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

import blake3
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

# Mirror gyza/identity.py's constants exactly.
_CTX_COMPOSITOR_SEED = b"gyza.compositor.ed25519.v1"
_CTX_AGENT_SEED = b"gyza.agent.ed25519.v1"


def _derive_seed(master: bytes, context: bytes, info: bytes) -> bytes:
    return blake3.blake3(context + b"|" + info, key=master).digest()


def main() -> None:
    # Fixed test master seed. Must match the constant in the Rust test
    # module (TEST_MASTER).
    master = bytes.fromhex(
        "0102030405060708090a0b0c0d0e0f10"
        "1112131415161718191a1b1c1d1e1f20"
    )

    print("# Rust parity-test fixtures generated by Python reference.")
    print("# Update the corresponding constants in gyza-crypto/src/lib.rs::tests.")
    print()

    # 1) BLAKE3 of empty input.
    print(f"blake3('') = {blake3.blake3(b'').hexdigest()}")
    print(f"blake3([0]) = {blake3.blake3(bytes([0])).hexdigest()}")
    print()

    # 2) Compositor seed (derive_seed with empty info).
    comp_seed = _derive_seed(master, _CTX_COMPOSITOR_SEED, b"")
    print(f"compositor_seed = {comp_seed.hex()}")

    # 3) Agent seed (derive_seed with non-empty info).
    agent_seed = _derive_seed(master, _CTX_AGENT_SEED, b"agent-0001")
    print(f"agent_seed[agent-0001] = {agent_seed.hex()}")
    print()

    # 4) Ed25519 pubkey from compositor seed.
    comp_sk = Ed25519PrivateKey.from_private_bytes(comp_seed)
    comp_pk = comp_sk.public_key().public_bytes_raw()
    print(f"compositor_pubkey = {comp_pk.hex()}")
    print()

    # 5) Ed25519 signature of "hello gyza" under the compositor key.
    msg = b"hello gyza"
    sig = comp_sk.sign(msg)
    print(f"sig(compositor, 'hello gyza') = {sig.hex()}")

    # 6) Agent pubkey + sig for completeness.
    agent_sk = Ed25519PrivateKey.from_private_bytes(agent_seed)
    agent_pk = agent_sk.public_key().public_bytes_raw()
    print(f"agent_pubkey[agent-0001] = {agent_pk.hex()}")
    agent_sig = agent_sk.sign(msg)
    print(f"sig(agent[agent-0001], 'hello gyza') = {agent_sig.hex()}")


if __name__ == "__main__":
    main()
