#!/usr/bin/env python3
"""
Regenerate Rust parity fixtures for `gyza-rs/gyza-canonjson`.

The Rust crate must produce bytes byte-identical to Python's
`json.dumps(obj, sort_keys=True, separators=(",", ":"))`. This script emits
the Rust `assert_eq!` lines with Python's REAL output already escaped for a
Rust raw string, so the fixtures can be pasted without hand-transcription.

NEVER hand-write the expected value. The first attempt at these fixtures was
written from the specification and typed literal `é` and literal control
characters into the Rust source, so six tests failed against a CORRECT
implementation. Silent divergence at the serialization layer is the entire
failure mode these fixtures defend against; a hand-written expectation
defends against nothing.

Usage:
    ~/dev/marshal/.os/bin/python gyza-rs/scripts/regenerate_canonjson_fixtures.py
"""
from __future__ import annotations

import json

# Each probe must be capable of DISTINGUISHING two implementations.
# Trivial agreement (plain ASCII) proves nothing and is included only as a
# control that the escaper leaves ordinary text alone.
CASES: list[tuple[str, str]] = [
    ("ascii",              "abc"),
    ("solidus",            "a/b"),
    ("quote",              'a"b'),
    ("backslash",          "a\\b"),
    ("newline",            "a\nb"),
    ("tab",                "a\tb"),
    ("cr",                 "a\rb"),
    ("backspace",          "a\bb"),
    ("formfeed",           "a\fb"),
    ("vtab_0x0b",          "a\x0bb"),
    ("null_0x00",          "a\x00b"),
    ("us_0x1f",            "a\x1fb"),
    ("tilde_0x7e",         "\x7e"),
    ("del_0x7f",           "a\x7fb"),
    ("latin1_e9",          "café"),
    ("combining_nfd",      "café"),
    ("cjk",                "中文"),
    ("bmp_max",            "￿"),
    ("nbsp_a0",            "a b"),
    ("rtl_mark",           "a‏b"),
    ("astral_emoji",       "x\U0001F510y"),
    ("astral_max",         "\U0010FFFF"),
]


def rust_input(s: str) -> str:
    """Render the INPUT as a Rust string literal using \\u{...} escapes."""
    out = []
    for ch in s:
        cp = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif 0x20 <= cp < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{{{cp:x}}}")
    return '"' + "".join(out) + '"'


def main() -> None:
    print("// GENERATED by gyza-rs/scripts/regenerate_canonjson_fixtures.py")
    print("// Expected values are Python's REAL json.dumps output. Do not edit by hand.")
    for name, s in CASES:
        expected = json.dumps(s)          # the actual Python bytes, quotes included
        # Expected contains only ASCII by construction (ensure_ascii=True), so a
        # Rust raw string carries it verbatim -- no double-escaping to get wrong.
        assert expected.isascii(), f"{name}: expected must be ASCII"
        assert '"#' not in expected, f"{name}: would break the raw string"
        print(f'        // {name}')
        print(f'        assert_eq!(py({rust_input(s)}), r#"{expected}"#);')

    # A structural probe: non-ASCII KEY, to prove keys route through the
    # same formatter as values.
    obj = {"café": 1, "a": [3], "b": [1, 2]}
    print()
    print("        // object with a non-ASCII KEY + compact separators")
    print(f'        // python: {json.dumps(obj, sort_keys=True, separators=(",", ":"))}')


if __name__ == "__main__":
    main()
